### ISSUE TITLE
Only able to see stat size of file, not able to see parsed size

### ISSUE THREAD

**Issue by raushankumarnitdgp** [webpack-contrib/webpack-bundle-analyzer#125]
#### Issue description
Only able to see stat size of file, not able to see parsed size. Or **

> **is there anyway to get parsed size of file instead of regular file size in stats.json**

**

#### Technical info
* Webpack Bundle Analyzer version: "webpack-bundle-analyzer": "^2.9.0",
* Webpack version: "webpack": "^3.0.0",
* Node.js version: v8.6.0
* npm/yarn version: 5.5.1
* OS: Ubuntu 14.04 LTS

#### Debug info
How do you use this module? As CLI utility or as plugin?
First I created stats.json using
`./node_modules/.bin/webpack --profile --json > stats.json`
then using 
`./node_modules/.bin/webpack-bundle-analyzer stats.json`
generated Tree Map

then in generated Tree Map only **stat** option is there
If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```
new BundleAnalyzerPlugin({
      analyzerMode: 'static',
      reportFilename: '../../webpack-analyser/index.html',
      statsFilename: './webpack-analyser/data/stats.json',
      defaultSizes: 'parsed'
    }));
```

What other Webpack plugins were used?

It would be nice to also attach webpack stats file.
It can be generated using these options:
stats.json generated using  `./node_modules/.bin/webpack --profile --json > stats.json`
```
`stats.json` will be created in Webpack bundle output directory.

**Comment by valscion** [comment]
Hmm sounds like webpack-bundle-analyzer has trouble parsing your bundled code.

Are you able to zip your bundles and your stats.json, and upload it here? If you don't want to publicly paste your code here, feel free to send it to me via email. My email address is visible in my GitHub profile: https://github.com/valscion

**Comment by raushankumarnitdgp** [comment]
is it possible to generate stats.json containing size of file as parsed size or minified file size.

**Comment by valscion** [comment]
Unfortunately no.

`webpack-bundle-analyzer` calculates the parsed and minified file sizes by reading your bundled source files, and that is one of its main purposes.

**Comment by valscion** [comment]
Discussion continued via email and @raushankumarnitdgp sent me this:

> Thank you very much for your help. I fixed the issue in different way :)😊
> 
> Raushan

So I'll close this issue now.

**Comment by smashercosmo** [comment]
Having the same issue: I can see only stat sizes. Any receipt?

webpack v3.10.0
webpack-bundle-analyzer v2.11.0

**Comment by th0r** [comment]
@smashercosmo could you paste console output here?

**Comment by valscion** [comment]
@smashercosmo better yet, please open a new issue and paste the console output as asked by @th0r above. Replying to closed issues makes it very difficult to track and help resolve.
