### ISSUE TITLE
Webpack 3 - Parsed size larger than stat size?

### ISSUE THREAD

**Issue by everettwho** [webpack-contrib/webpack-bundle-analyzer#128]
#### Issue description

Hello! 

I'm not 100% sure this is the right place to be posting, but I don't think any other repo would have the right context for this issue. I recently upgraded my app to Webpack 3 from Webpack 1 and saw an increase in the final gzipped bundle size. I found that strange because on the surface level the stats size of the Webpack 3 bundle was a good ~10% smaller than the Webpack 1 bundle. 

After a bit of digging around, I found that if I remove UglifyJsPlugin as a plugin from my Webpack 3 config and look at the bundle report, the parsed size is actually larger than the stats size. Doing the same thing in my Webpack 1 config results in a smaller parsed size than stats size. Besides syntax and deprecation changes from the upgrade, my Webpack 1 and Webpack 3 configs should be the exact same.

I'm not sure if this is something strange going on in `webpack-bundle-analyzer` and Webpack 3, but if not I'm wondering if anyone has insight as to why a bundles parsed size might be larger than its stats size without UglifyJs minification.  

#### Technical info
* Webpack Bundle Analyzer version: 2.9.0
* Webpack version: 3.8.1
* Node.js version: 6.9.1
* npm/yarn version: 3.10.8
* OS: OSX El Capitan 10.11.6

#### Debug info
How do you use this module? As CLI utility or as plugin? Plugin

```
new BundleAnalyzerPlugin({
    analyzerMode: 'server',
    analyzerHost: '127.0.0.1',
    analyzerPort: 8888,
    reportFilename: 'report.html',
    defaultSizes: 'parsed',
    openAnalyzer: true,
    generateStatsFile: false,
    logLevel: 'info'
  }),
```

What other Webpack plugins were used?

```
new ExtractTextPlugin(`css/bundle.${webpackHash}.css`),
new webpack.NoEmitOnErrorsPlugin(),
new UglifyJsPlugin(),
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
```

**Comment by th0r** [comment]
What is the difference between stat and parsed sizes?

**Comment by everettwho** [comment]
Hmmmmm it looks like something related to tree-shaking, Lodash, and the way we try to reduce the size of Lodash in our bundle is causing the problem. I don't think this is a problem with `webpack-bundle-analyzer`. Sorry to bother you guys!

**Comment by valscion** [comment]
Glad the issue was resolved :). Thanks for following up!

**Comment by valscion** [comment]
@xiaoyanzheng please open a new issue for your case
