### ISSUE TITLE
License violation(?) in treemap widget

### ISSUE THREAD

**Issue by evmar** [webpack-contrib/webpack-bundle-analyzer#132]
This repository says it is MIT licensed, but it includes this code:
https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/client/vendor/carrotsearch.foamtree.js
which does not appear to be MIT licensed but rather "Carrot Search confidential. / Copyright 2002-2016, Carrot Search s.c, All Rights Reserved."

[Disclaimer: I am the author of a different [treemap widget](https://github.com/evmar/webtreemap).  I discovered this issue because I was curious about where you got your treemap widget from.]

**Comment by valscion** [comment]
I am not a lawyer, but if I've understood it correctly, having a different LICENSE declaration in https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/client/vendor/carrotsearch.foamtree.js is enough to show that it isn't licensed under MIT.

```
/**
 * Carrot Search FoamTree HTML5 (demo variant)
 * v3.4.4, 36955f78f6b79223438db3b18b9b64b5aad799bb/36955f78, build FOAMTREE-SOFTWARE4-DIST-26, Sep 23, 2016
 * 
 * Carrot Search confidential.
 * Copyright 2002-2016, Carrot Search s.c, All Rights Reserved.
 */
```

Maybe someone else in @webpack-contrib is more well versed with these questions?

**Comment by evmar** [comment]
Generally you cannot reused copyrighted code in a combined work and claim
the larger work has a less restricted license.

The license must explicitly allow you to use it in a combined work. For
example, MIT does, and apache2 calls it out:
https://opensource.stackexchange.com/questions/960/how-does-one-combine-differently-licensed-code-in-one-open-source-program

You might ask the author of this code for permission to redistribute in
this manner. They might be happy with it.

**Comment by Stephanemw** [comment]
Looks like the Foamtree website covers this on their homepage and on their free-trial page:

https://carrotsearch.com/foamtree/free-trial/
> **Do I need a trial license to evaluate FoamTree?**
> No. The trial version is perpetual and does not require a license file to run. Instead, it displays a small FoamTree logo in the visualization area.
> 
> **Can I use the demo version in a commercial project?**
> Yes, feel free to use the demo version in your project free of charge. The only requirement is that you must not remove or obscure the FoamTree logo the demo version displays.

The generated reports shows the logo and it links to their website. Perhaps some attribution in the main README would help others with this question too.

**Comment by valscion** [comment]
I think the foamtree code has been communicated clearly enough that it is 3rd party code and is similar in nature to how npm dependencies work.

If anyone from Carrot Search contacts us on this, we can rethink a best way to handle this.

**Comment by evmar** [comment]
It's up to you, but there is definitely a difference between:
- making a program that can use proprietary code from npm or somewhere else
- copying code into your program

For example, if you made an iOS program, you would of course use Apple copyrighted libraries in that program.  But if you copied those Apple libraries into your github repository, you'd be in trouble.

I don't mean to harass you about it -- I've had people randomly copy my code in the past and it really bugged me.  Feel free to leave this closed and thanks for looking into it!

**Comment by th0r** [comment]
@evmar could you explain the difference between requesting dependency from `npm` and including *unmodified* code into your own repository?
