### ISSUE TITLE
Feature request: Reduced text/json "summary" of bundle sizes

### ISSUE THREAD

**Issue by cngu** [webpack-contrib/webpack-bundle-analyzer#136]
#### Request description
My end goal is to have a CI build track bundle sizes over time. 

To accomplish this, I'd like all the "top-level bundle/chunk names" to "stat/parsed/gzip size" mappings (essentially all the existing data being displayed in the left sidebar of the interactive index.html report), but in a simpler text or json output file to make it easier for the CI build retrieve this data.

* sizes would preferably be in bytes
* the combined size (listed as "All" in the left sidebar) would be nice if it isn't too much extra effort
* I have no other preferences on the output file format, so long as it's fairly straightforward to parse the 3 sizes for each bundle/chunk

Thanks for your hard work on this amazing plugin!

**Comment by th0r** [comment]
Hi! There is a [WIP PR](https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/97) by @valscion that will allow to use any custom reporter instead of the built in one so you'll be able to simply generate some JSON (or whatever) file with the info you need.

**Comment by valscion** [comment]
@cngu thanks for the issue! th0r is right, my PR will make it possible to implement this kind of reporter easily. It's encouraging to hear that there is demand for this kind of feature -- I've been slighly demotivated at times to work on the version 3 PR as I haven't been sure if people would need it

**Comment by cngu** [comment]
@th0r @valscion Thanks guys! Version 3 sounds great, I'm looking forward to it! I can see how it might be demotivating, but there's definitely demand, even if it's only to update the plugin architecture, make contributions easier, get new users trying out the shiny new v3, etc. This plugin is essential in my opinion -- it's even included by default in the official Vue webpack template!
