### ISSUE TITLE
Add source map support

### ISSUE THREAD

**Issue by ai** [webpack-contrib/webpack-bundle-analyzer#139]
**TLTR:** feature request to split files in Webpack stats according to source map files.

Thanks for the awesome tool. I used it in [Size Limit](https://github.com/ai/size-limit) to prevent JS libraries bloat. Autoprefixer, PostCSS, Material UI, MobX uses Size Limit.

Size Limit creates empty webpack project add your open source JS libraries and calculate project size difference to get real cost of your library for your users:

> lib files and dependencies → empty webpack project → library’s real cost

Also, my tool has `size-limit --why` mode which adds Webpack Bundle Analyzer to this empty webpack project and shows the reason of library real cost (for example, you import whole `lodash` instead of separated files).

It works great on many projects. But some projects don’t publish many small files to npm. They publish one big JS bundle file created by their own builder (mostly Rollup)

> lib files and dependencies → rollup → single bundle file → empty webpack project → library’s real cost

In this case `size-limit --why` will not work anymore, because Webpack Bundle Analyzer sees only that single bundle.

If we will add source map support, we will be able to see small files again. For example, we can put some filter for webpack stats. If we have `dist/lib.js` in stats and we found `dist/lib.js.map`, we split `dist/lib.js` stats to separated files according to source map.

Don’t worry, I will implement it on my own (ask my friends to do it) and send the pull request. I have only a few questions:

1. What do you think about it? Feel free to ask questions, I think I don’t describe the idea very well :(.
2. Should we add special option and use source map only if this option will be set to `true`?
3. Maybe there is a way to extend Webpack Bundle Analyzer and more all this source map magic to some separated project?

**Comment by valscion** [comment]
Hi! This seems like a neat idea!

However, I'm afraid this will be out of scope of `webpack-bundle-analyzer`. We specifically work from the stats file generated by webpack and use that as the module source of truth — sourcemaps would be completely different from this. I'm more worried about the maintenance burden than I am about implementing the first pass of this feature.

Maybe your use case would be solvable by some other tool that uses sourcemaps? Have you checked out [`source-map-explorer`](https://github.com/danvk/source-map-explorer)?

**Comment by ai** [comment]
@valscion I agree that this feature is not useful for everyone. So I agree with you that it will be better to add this feature as some sort of addition step between webpack and `webpack-bundle-analyzer`.

I am not sure that it is out of `webpack-bundle-analyzer` goal. More detailed bundle analysis is always useful.

`source-map-explorer` looks nice, but we need a server and better design. As result, we need just copy 80% of `webpack-bundle-analyzer` :(.

What do you think if we add `filter` option, which will be applied to webpack stats. This PR will be very small and will not be hard to maintain. 

Then we will use it in Size Limit to split stats. And some different tools could use `filter` too, because it is flexible.

**Comment by valscion** [comment]
I don't think it will be possible to get parsed or gzip support in, even if we'd have a step between sourcemaps and `webpack-bundle-analyzer`. This tool parses the bundles generated by webpack and then maps modules using AST-based search to the actual module names discovered from webpack stats file. I don't think it will be possible to do that with sourcemaps.

Feel free to try out if it can be done, but I'm pretty sure we won't be accepting sourcemap based analysis any time soon, sorry.
