### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [webpack-contrib/webpack-bundle-analyzer#141]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, so it may be a good idea to use it instead of EJS 😀

**Comment by th0r** [comment]
Thanks for the proposal, but does it have any other benefits in addition to speed? I'm asking because speed is not critical here at all.

**Comment by Drulac** [comment]
It use less CPU and RAM ressources

**Comment by th0r** [comment]
Sorry, but I don't see any serious benefits of replacing it with your template engine.
