### ISSUE TITLE
Feature: Show size next to the name

### ISSUE THREAD

**Issue by DioNNiS** [webpack-contrib/webpack-bundle-analyzer#144]
It will be nice to have an option to shown module/file size next to the name. 
The same as it implemented in https://github.com/danvk/source-map-explorer.

It will help to analyze report if the screenshot has been taken and without mouse moves...

**Comment by valscion** [comment]
Hi! Thanks for the suggestion :relaxed:. I don't think we will take this on anytime soon, so I'll close this issue. We'll keep this idea in mind, though!
