### ISSUE TITLE
Doesn't parse child workerize'd module

### ISSUE THREAD

**Issue by whitecolor** [webpack-contrib/webpack-bundle-analyzer#150]
#### Issue description
I use https://github.com/developit/workerize-loader to bundle some scripts for webworker, but bundle analizer doesn't parse and display it.

#### Technical info
* Webpack Bundle Analyzer version: 2.10.0
* Webpack version: 3.5.5.

![image](https://user-images.githubusercontent.com/736697/35771207-77510c84-094a-11e8-8c71-6e8d11ab7c10.png)

As you see there is not `worker` module in the map:

![image](https://user-images.githubusercontent.com/736697/35771214-938cf9ee-094a-11e8-9377-0105bc2d3efd.png)

**Comment by valscion** [comment]
Nice find! Would you be able to provide a webpack stats JSON object for your build so we could take a closer look? If you don't want to share the stats JSON, could you create a small reproduction repository which showcases this issue?

It could be that worker chunks are a bit different, and we'd need to do extra work to be able to get them in to the visualization.

**Comment by whitecolor** [comment]
Think for you a better way to get what you need will be just adding basic workerized module test, just following instructions in the readme:

## Install

```sh
npm install -D workerize-loader
```


### Usage

**worker.js**:

```js
// block for `time` ms, then return the number of loops we could run in that time:
export function expensive(time) {
	let start = Date.now(),
		count = 0
	while (Date.now() - start < time) count++
	return count
}
```

**index.js**: _(our demo)_

```js
import worker from 'workerize-loader!./worker'

let instance = worker()  // `new` is optional

instance.expensive(1000).then( count => {
	console.log(`Ran ${count} loops`)
})
```

**Comment by valscion** [comment]
Setting up a new project is too much trouble right now for the time I have. Would you be able to setup an example project with this where the stats.json could be generated easily?

**Comment by whitecolor** [comment]
Will try.

**Comment by brendanmoore** [comment]
Same issue with `worker-loader`

A snippet from my stats file
```json
    {
      "name": "static/js/958ecd6b.worker.js",
      "size": 5622520,
      "chunks": [],
      "chunkNames": [],
      "emitted": true,
      "isOverSizeLimit": true
    }
```
Ignored because chunks is empty: (`analyzer.js`) 
```javascript
 // Picking only `*.js` assets from bundle that has non-empty `chunks` array
  bundleStats.assets = _.filter(bundleStats.assets, asset => {
    // Removing query part from filename (yes, somebody uses it for some reason and Webpack supports it)
    // See #22
    asset.name = asset.name.replace(FILENAME_QUERY_REGEXP, '');

    return _.endsWith(asset.name, '.js') && !_.isEmpty(asset.chunks);
  });

```
https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/src/analyzer.js#L34

**Comment by nolanlawson** [comment]
I ran into this same issue with my OSS project [Pinafore](https://github.com/nolanlawson/pinafore). Unfortunately I couldn't manage to write a minimal repro; my [minimal repro](https://gist.github.com/nolanlawson/ee03ecf41521036cc46c6be1aca1b77c) still shows `worker.js` correctly in Webpack Bundle Analyzer.

It's not a _minimal_ repro, but if you'd like to repro the issue, you can do:

    git clone https://github.com/nolanlawson/pinafore.git
    cd pinafore
    git checkout 65c026a3
    npm i
    npm run build

Then open up `./.sapper/client/report.html` to see the report.

**Comment by valscion** [comment]
Thanks @nolanlawson! Those repro steps will likely be useful once we get to debugging this

**Comment by th0r** [comment]
@nolanlawson do you still face this issue?

**Comment by whitecolor** [comment]
> @nolanlawson do you still face this issue?

I'm using webpack-bundle-analyzer@3.0.3, should I upgrade to see the issue disappear?

**Comment by valscion** [comment]
Maybe try upgrading and report back if this is still an issue @whitecolor?

**Comment by whitecolor** [comment]
> Maybe try upgrading and report back if this is still an issue @whitecolor?

No, nothing changed, I don't see workerized bundles.

**Comment by valscion** [comment]
Thanks for testing

**Comment by masterkidan** [comment]
Any update on this issue?

**Comment by valscion** [comment]
A minimal reproduction repository would help decipher what's happening

**Comment by masterkidan** [comment]
Can you not use Nolan's example above?

**Comment by valscion** [comment]
This makes it more difficult:

> Unfortunately I couldn't manage to write a minimal repro

**Comment by universse** [comment]
I'm facing the same problem. Hopefully this repro can help https://github.com/universse/workerize-bundle

It's a gatsby app. The relevant config is in gatsby-node.js. Worker code is in ```src/firebase.worker.js```, which I import in ```pages/index.js```.

**Comment by valscion** [comment]
Ok good to know that it happens with small tweaks to gatsby default configuration. Would be ace if we could have a reproduction with only webpack — so we wouldn't have to decipher what parts in the gatsby+webpack combination cause this failure.

**Comment by nolanlawson** [comment]
I'm still running into this issue, and haven't been able to find a minimal repro unfortunately. (My repro steps above should still work, though. :slightly_smiling_face:)

That said, I analyzed a bit using `node --inspect`, and I noticed that at this line of code, the `stats` object already doesn't contain the worker asset inside of `stats.toJson().assets`:

https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/7cefb5821053f550754b4fef3ca5a57ce49dc957/src/BundleAnalyzerPlugin.js#L36-L37

I checked by doing `stats.toJson().assets.filter(_ => _.name.includes('worker'))` (my asset happens to include `worker` in there). I don't see it in `stats.toJson().chunks` either.

Oddly, though, the asset _is_ inside of `stats.compilation.assets`. So it looks like this may be an issue with the `stats.toJson()` function? I notice that it accepts [several options](https://github.com/webpack/webpack/blob/11e94dd2d0a8d8baae75e715ff8a69f27a9e3014/lib/Stats.js#L145-L230), but we aren't passing any in. Maybe one of these options would show the missing worker asset?

My versions are `webpack@4.41.2` and `webpack-bundle-analyzer@3.5.2`.

**Comment by valscion** [comment]
Yeah if anyone who is stumbling on this is willing to debug further, it would make it more likely that this would get fixed :smile:

I don't myself need this support yet, and I don't have extra time to prioritize fixing this bug unfortunately.

**Comment by nolanlawson** [comment]
I think I've managed to track this issue down. It seems that my worker assets have `asset.chunks.length === 0`. So when it gets to this line of code, it gets filtered out:

https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/7cefb5821053f550754b4fef3ca5a57ce49dc957/src/analyzer.js#L39

When I remove the `!_.isEmpty(asset.chunks)` check, then I correctly see my worker assets in the Webpack Bundle Analyzer view. I'm not sure what this empty check was doing, though. Is it safe to remove?

**Comment by masterkidan** [comment]
https://github.com/masterkidan/worker-loader-no-stats

@valscion : Apologies for the really slow repro on this, but here's a minimal repro
run yarn build:analyze and you will see the following
![image](https://user-images.githubusercontent.com/942002/90569480-cec0ae00-e162-11ea-82bc-53d735c1d0ef.png)

where the assets created by the worker-loader are not present. I think this is related to the earlier fact that childChunks are not being computed for worker assets for some reason

**Comment by masterkidan** [comment]
@nolanlawson : While I do agree that your fix produces the bundle, its very hard to perform bundle reduction without understanding what the constituents of the bundle are. For that reason, I don't think that should be the fix here

**Comment by masterkidan** [comment]
After debugging a bit, it looks like this a rendering/display issue with analyzer.js, I've opened a PR with the fix that generates the view for the worker bundles as well @nolanlawson , can you see if it works for you?

**Comment by th0r** [comment]
@valscion @masterkidan does https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/376 fix this?

**Comment by masterkidan** [comment]
Yes I believe so
