### ISSUE TITLE
High cpu on docker container due to webpack analyzer 

### ISSUE THREAD

**Issue by diiaann** [webpack-contrib/webpack-bundle-analyzer#153]
#### Issue description
In between `2.9.1` and `2.10.1` we noticed that upon starting our webpack build, our rebuilds were extremely slow. After the initial webpack build command, cpu usage would shoot up to >99% and stay there. Thus subsequent rebuilds due to the watch command would take minutes instead of the usual second.  Holding everything constant and pinning the version of `webpack-bundle-analyzer` to `2.9.1` caused the issue to go away.

#### Technical info
* Webpack Bundle Analyzer version:
`2.10.1`
* Webpack version:
`3.11.0`
* Node.js version:
`v6.12.0`
* npm/yarn version:
`3.10.10`
* OS:
Docker for Mac on MacOS Sierra , with this container
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
```
#### Debug info
> How do you use this module? As CLI utility or as plugin?

Plugin

> If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

```
      new BundleAnalyzerPlugin({
        analyzerMode: 'static',
        analyzerPort: 8888,
        reportFilename: 'webpackReport.html',
        openAnalyzer: false,
        generateStatsFile: true,
        statsFilename: 'stats.json',
      })
```

**Comment by valscion** [comment]
Hi! Thanks for the detailed issue, I'll look into it.

When you say "version `2.10.1`", you probably mean `2.10.0`, right? I don't think we've published a patch release after `2.10.0` ☺️

**Comment by valscion** [comment]
Could you try running with `generateStatsFile: false`? It's likely that your high CPU usage is due to https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/129. Could you verify that version `2.9.2` still works for you, so that we can be sure the regression happened between 2.9.2 and 2.10.0?

**Comment by valscion** [comment]
Hi @diiaann, have you had a chance to look into my earlier comment? ☝️

**Comment by th0r** [comment]
Closed due to inactivity.
