### ISSUE TITLE
Output does not reflect what bundle-analyzer shows

### ISSUE THREAD

**Issue by Legends** [webpack-contrib/webpack-bundle-analyzer#163]
#### Issue description
The bundle-analyzer stats show:
jQuery and RoundSlider.min.js

But there are ~4 more modules inside of `view.default.index.chunk.js` chunk?!

![image](https://user-images.githubusercontent.com/966368/38064965-0d3ef582-3301-11e8-811c-adc94826df42.png)

#### Technical info
* Webpack Bundle Analyzer version:   "version": "2.11.1",
* Webpack version: 4.3.0
* Node.js version: 8.10
* npm/yarn version: 5.8
* OS: win 10 x 64

#### Debug info
How do you use this module? As CLI utility or as plugin?
```
 new BundleAnalyzerPlugin({
            analyzerMode: "static",
            openAnalyzer: true,
            generateStatsFile: true,
            // Excludes module sources from stats file so there won't be any sensitive data
            statsOptions: { source: false }
        }),
```
If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

What other Webpack plugins were used?
```
const webpack = require("webpack"); //to access built-in plugins
const CleanWebpackPlugin = require("clean-webpack-plugin")
var ExtractTextPlugin = require("extract-text-webpack-plugin")
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const merge = require('webpack-merge');
const HTMLWebpackPlugin = require('html-webpack-plugin');
```
[stats.log](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1858366/stats.log)

**Comment by valscion** [comment]
Hi! Nice to see you here ☺️ 

> But there are ~4 more modules inside of view.default.index.chunk.js chunk?!

Could you please clarify? Are these ~4 more modules visible in the screenshot you posted?

**Comment by Legends** [comment]
Hi :-)
No, there are not visible, that's why I ask. Shouldn't they be visible in the screenshot?

**Comment by valscion** [comment]
Ooh so you have _more_ modules than is visible, right? I understood that you meant that the screenshot has _too many_ modules, not _too little_ :smile:

**Comment by valscion** [comment]
And yes, your modules are visible in the screenshot — they're just so so minimal compared to the size of jquery and roundslider you have there:

![screen shot 2018-03-29 at 14 07 33](https://user-images.githubusercontent.com/482561/38085812-99f635c2-335a-11e8-9347-47181dafbd2c.png)

I opened your stats.json (thanks for providing it!) and I saw the modules there:

![screen shot 2018-03-29 at 14 08 24](https://user-images.githubusercontent.com/482561/38085825-b5fdd4be-335a-11e8-9dc1-c8a6e84b1169.png)

**Comment by Legends** [comment]
In the middle of the black line? haha... I have to check that.

An improvement would be, to make jQuery (bigger bundles) smaller, but super little ones bigger...
There should be such thing as a minimum size.

Just a thought...

**Comment by valscion** [comment]
> There should be something like a minimum size. [...] super little ones bigger

Yeah that might be a good idea. Having the visualization collapse very small chunks to nearly invisible lines isn't very user friendly 😅 



> An improvement would be, to make jQuery (bigger bundles) smaller

We precisely want to highlight huge dependencies, like jquery, so you can easily spot them from the rest of the output. Once your projects start to grow, then this UI problem will be less of an issue.

> Just a thought...

Thanks for the input :relaxed:

**Comment by Legends** [comment]
I guess, I am using the wrong plugin then, which one would you recommend, if someone wants to see which modules are in which chunk?

**Comment by valscion** [comment]
Hmm I don't know, sorry. You can keep on using this plugin to see it, just be mindful of small modules being very small in the UI.

I'd be interested to know what is your use case for needing to see which modules are in which chunk, while your own code is quite small, if you don't mind me asking?

**Comment by Legends** [comment]
I am switching to wp v4, and have some problems like empty css files (will try MiniCssExtractPlugin now) and yeah, it's different now and still didn't grasp wp v4, but I am on my way to explore it, that's why I compare configuration changes with output.. :-)

**Comment by valscion** [comment]
Ah ok :) good luck to your journey!
