### ISSUE TITLE
Finds stats but not rendering, console error: Uncaught FoamTree: element has zero dimensions

### ISSUE THREAD

**Issue by esoyke** [webpack-contrib/webpack-bundle-analyzer#164]
#### Nothing rendered, getting error in console: 
`Uncaught FoamTree: element has zero dimensions: 0 x 0`

#### Technical info
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-dev-server": "^2.10.1"
* Node 6.9.5
* npm 3.10.10
* OSX

#### Debug info
Ran: 'npm run bundle-report', with this in package.json scripts section: "bundle-report": "webpack-bundle-analyzer dist/stats.json"

It launches the web page and apparently finds the stats file, when hovering over the left area of the page it lists main and polyfills chunks of sizes 5.49MB and 300KB respectively. However the inline and scripts chunks are both listed as 0 bytes. This doesn't match the sizes of those bundles in reality, in the file system those bundles are 1KB and 168KB?

I build the app with:
```
ng build --prod --aot=true --stats-json
```

(Renamed stats.json as stats.txt to pass the upload filter, FYI it's big: 8.9MB)
[stats.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1871768/stats.txt)

**Comment by mjamesderocher** [comment]
The page is blank, but the sidebar is loading.

**Comment by valscion** [comment]
Does the sidebar allow you to change the size used? Or is your stats size empty?

**Comment by mjamesderocher** [comment]
The sidebar allows you to change the size used. It has the checkboxes to let you select what chunks to show. When clicking to change the size used, the console gives the error "Treemap.jsx:106 Uncaught (in promise) TypeError: Cannot read property 'update' of null"

**Comment by th0r** [comment]
> The situation that I am using it in is an example from the Next.js repo

Example works for me. I did this:
```
curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-webpack-bundle-analyzer
cd with-webpack-bundle-analyzer
npm i
npm run analyze
```

![1](https://user-images.githubusercontent.com/302213/38357984-c1f9edda-38cc-11e8-9dd6-c3684c297dd2.gif)

**Comment by mjamesderocher** [comment]
I'm using Windows 10. Node version is 8.9.4. NPM is 5.6.0.

**Comment by th0r** [comment]
@mjamesderocher and commands above open broken report for you?

**Comment by esoyke** [comment]
Apologies for the late reply, I was offline a few days and didn't see the updates. I too use the Windows Resizer extension, that was the culprit. Disabling it or using Incognito resolved it. Thanks guys!

**Comment by valscion** [comment]
Thank you for confirming, @esoyke :relaxed:
