### ISSUE TITLE
After migration to Angular 6 stats analyzer does not show full information

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [webpack-contrib/webpack-bundle-analyzer#174]
#### Issue description
I have migrated to Angular 6 and cannot see detailed info like it was the case with Angular 5
...

#### Technical info
* Webpack Bundle Analyzer version: 2.11.1
* Webpack version: 4.6.0
* Node.js version: 9.8.0
* npm/yarn version: 5.6.0
* OS: Windows 10

#### Debug info
As a CLI. I am running command `ng build --prod --stats-json`

What other Webpack plugins were used? No, At least Angular CLI uses something under the hood

[stats.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1986968/stats.zip)

**Comment by valscion** [comment]
Try running

```
ng build --stats-json --build-optimizer=false --vendor-chunk=true
```

**Comment by vytautas-pranskunas-** [comment]
Same result:

![image](https://user-images.githubusercontent.com/3918999/39805027-f1551ff0-5375-11e8-8c34-182d34e71f8c.png)

**Comment by th0r** [comment]
Seems like the structure of `stats.json` have changed and now we incorrectly extract module information.

**Comment by valscion** [comment]
We will fix it when we have time

**Comment by th0r** [comment]
Should be fixed in `v2.11.2`

**Comment by TomDemulierChevret** [comment]
It is indeed fix'd with the new version for my current angular CLI project.
A big thank to your reactivity !

**Comment by jpduckwo** [comment]
Great work thanks!
