### ISSUE TITLE
Turn off text display

### ISSUE THREAD

**Issue by stefanhayden** [webpack-contrib/webpack-bundle-analyzer#179]
This is a weird request but I wish I could render the graph without the filenames. I want to share on social media my cool my cool layout with different packages but I don't think my company wants me publishing our whole dependency tree.

**Comment by th0r** [comment]
I would suggest you to generate `report.html`, open it in some text editor and replace all `"label": "..."` entries with `"label": ""`. That should work.

**Comment by stefanhayden** [comment]
sounds good! I'll give it a try!
