### ISSUE TITLE
Confusing bundle visualization for main bundle

### ISSUE THREAD

**Issue by bugzpodder** [webpack-contrib/webpack-bundle-analyzer#189]
https://expirebox.com/download/380d419c6134d02181b9ef6f4431e576.html

Each path is showing up twice in the main bundle.  Eg:
automation: Stat size: 208.87kb
automation: Stat size: 48.95kb Parsed Size: 25.61kb

**Comment by valscion** [comment]
Would you be able zip the contents of your bundle files (if using CRA, the contents of `build/`) directory and upload them here? If the `bundle-stats.json` is there, note that it will include your source code as well. If you'd rather not upload them here, you can send them to me or @th0r via email. Our mail addresses are visible in our GitHub profile page.

**Comment by valscion** [comment]
Let's discuss this case in #188 as well. We won't be able to get the zip of bundles so we can't debug this case much further.
