### ISSUE TITLE
[Feature request] use opn instead of opener

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/webpack-bundle-analyzer#190]
Hi,

First thank you for this very nice package !
Just notice something that could be improved.

Actually **webpack-bundle-analyzer** use **[opener](https://www.npmjs.com/package/opener)** to open a browser window with the analyzer.

Sadly this package is very old and not really maintain.
Also it doesn't offer open option too choose which browser to use when open a url.

As many people use a different browser for development and for browsing it could be nice to have such choice.

So why not using the very well maintain **[opn](https://www.npmjs.com/package/opn)** to implement this easily?

Cheers

**Comment by valscion** [comment]
Seems like `opener` is maintained. I'll close this issue for now.
