### ISSUE TITLE
Document webpack-dev-server interplay only displaying stat sizes

### ISSUE THREAD

**Issue by valscion** [webpack-contrib/webpack-bundle-analyzer#191]
The closed issue #147 has some valuable comments about `webpack-bundle-analyzer` only showing stat sizes when bundle output does not go to the filesystem.

It would be valuable to document this caveat in the README.md.

## This contribution opportunity has been seized by @fanich37

**Please avoid creating competing pull requests**

---

Here's some background from the linked issue:

@jeron-diovis in https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/147#issuecomment-380737178

> Just ran into this issue using analyzer with `webpack-dev-server`. No angular or things like this. 
> 
> The problem is that analyzer uses physical files to calc parsed/gzipped sizes – while `webpack-dev-server` keeps everything in memory.
> 
> Second problem is that being used as plugin, analyzer shows no errors, while CLI tools says `Couldn't parse bundle asset`.
> 
> As I understand, there is nothing analyzer can do with `webpack-dev-server`, but maybe it's worth to explicitly mention in docs that you should have files on disc to get parsed/gzipped info?

@AgentME in https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/147#issuecomment-397444503

> I was using webpack with gulp and `compiler.outputFileSystem = new MemoryFS();` so that webpack wouldn't write the bundles itself, so I ran into the same issue as @jeron-diovis. The BundleAnalyzerPlugin didn't report any errors at all in the console, just silently produced stat-sized-only reports. I had to use `webpack-bundle-analyzer` on the command line on the profile json in order to see any kind of error message, which I only thought to do because of this thread.

**Comment by fanich37** [comment]
Hi, @valscion . May I take this one?

**Comment by valscion** [comment]
Sure! :+1:

**Comment by Knogobert** [comment]
This should perhaps be updated in the docs to the current error string, which (for me) is: 
```
Error parsing bundle asset "your_bundle_name.bundle.js": no such file
No bundles were parsed. Analyzer will show only original module sizes from stats file.
```

Rather than the outdated:
```
Couldn't parse bundle asset "your_bundle_name.bundle.js".
Analyzer will use module sizes from stats file.
```

If I'm not mistaken.

**Comment by valscion** [comment]
Hmm yeah, makes sense. Feel free to open a PR to change the docs.

I wonder when the outdated text was changed, or whether it comes from some other place in the code that I now don't recall...

**Comment by kanishk30** [comment]
I am facing similar issues. I can only see Stat after running bundle analyser. 
<img width="755" alt="Screenshot 2021-11-23 at 7 16 44 PM" src="https://user-images.githubusercontent.com/34736432/143035682-ae27be35-4793-48f0-b739-148c0a4f6cf4.png">

Just adding following line makes it happen,
**'react-dates/lib': 'react-dates/esm'**
```
 resolve: {
      modules: [path.resolve(__dirname), 'node_modules'],
      alias: {
        ....
        'react-dates/lib': 'react-dates/esm'
      },
```

If I remove this line, I am able to see all three ( Stat, Parse, Gzipped)

**Comment by valscion** [comment]
Please open a new issue and fill the issue template.
