### ISSUE TITLE
Switch bfj-node4 to bfj?

### ISSUE THREAD

**Issue by ryanpcmcquen** [webpack-contrib/webpack-bundle-analyzer#198]
Got this warning when installing `webpack-bundle-analyzer`:
```
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new
features!
```

**Comment by valscion** [comment]
Hi! Thanks for opening an issue.

Too bad that `bfj-node4` has decided to start showing a warning after installing 😞.

We will most likely get to this when we update dependencies.

**Comment by ryanpcmcquen** [comment]
Sounds good, it looked low priority, but I figured the team would want to know.

**Comment by gknapp** [comment]
Any date for the next release & when this dependency bump will land?

**Comment by th0r** [comment]
@gknapp watch for https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/206 - it contains `bfj` update.

**Comment by th0r** [comment]
Updated in v3.
