### ISSUE TITLE
Remove node_modules from report and stats file

### ISSUE THREAD

**Issue by igorbrandao** [webpack-contrib/webpack-bundle-analyzer#201]
#### Remove node_modules from report and stats file

So, I need to generate a report and stats file containing only source files and no node_modules/vendor/third party. Tried that from both `excludeAssets` and `exclude` array within `statOptions` but no luck. How can one accomplish that? Thanks in advance!

#### Technical info
* Webpack Bundle Analyzer version: ^2.13.1
* Webpack version: 2.7.0
* Node.js version: 8.9.3
* npm/yarn version: 5.5.3
* OS: MacOS Sierra 10.12.6

#### Debug info
How do you use this module? As CLI utility or as plugin?

Plugin

```
new BundleAnalyzerPlugin({
    excludeAssets: ['node_modules', 'dev', 'vendor'],
    generateStatsFile: true,
    statsOptions: {
      exclude: ['node_modules', 'dev', 'vendor'],
      hash: false,
      cached: false,
      cachedAssets: false,
      reasons: false,
      source: true,
      warnings: false,
      errors: false,
      errorDetails: false,
      publicPath: false,
      modulesSort: 'size',
      chunksSort: 'size',
      assetsSort: 'size'
    }
})
```

What other Webpack plugins were used?

None

**Comment by bertho-zero** [comment]
```js
{
  statsOptions: {
    exclude: /node_modules/
  }
}
```
works for me.

**Comment by ismailshah99** [comment]
> ```js
> {
>   statsOptions: {
>     exclude: /node_modules/
>   }
> }
> ```
> 
> works for me.

also work for me

**Comment by valscion** [comment]
Great! Then this is resolved.
