### ISSUE TITLE
Change default port to something other than 8888

### ISSUE THREAD

**Issue by vjpr** [webpack-contrib/webpack-bundle-analyzer#202]
Charles Proxy for macOS defaults to this port for its proxy.

When debugging an app using `HTTP_PROXY=http://localhost:8888 npm start` to route all requests through Charles, it causes weird problems. Took me a long time to figure out.

**Comment by bstodola-lhi** [comment]
I believe you are able to change the port using the -p flag on the command.:
webpack-bundle-analyzer dist/stats.json -p 1234

**Comment by valscion** [comment]
Hi, you can indeed use `-p` flag to change to a different port. Or if using the plugin, use `analyzerPort` configuration option.
