### ISSUE TITLE
Does not work for entrypoints which do not end in `.js`

### ISSUE THREAD

**Issue by Tvrqvoise** [webpack-contrib/webpack-bundle-analyzer#207]
#### Issue description
This tool does not work with bundles which do not end in `.js`.  This is unfortunate for `react-native` projects (over [`haul`](https://github.com/callstack/haul)), as the default filenames end simply in `.bundle`.  This can be remedied [by modifying this line in analyzer.js](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/src/analyzer.js#L38):

```js
return _.endsWith(asset.name, '.js') && !_.isEmpty(asset.chunks) && isAssetIncluded(asset.name);
```

That being said, this doesn't appear too be a bug, per se -- indeed, it looks very intentional, and there's even a comment about this behavior:

```js
// Picking only `*.js` assets from bundle that has non-empty `chunks` array
```

As to *why* it only picks `.js` assets, I am unsure.  When I removed the check for `.js`, it started failing because it would attempt to parse the source maps, so I had to add `!_.endsWith('.map')`.  Does someone with context around this issue know why it filters against `.js` specifically, and if there might somehow be a better way?

**Comment by th0r** [comment]
The reason is to parse only assets that actually contain JS code. Maybe we could instead just try to parse each asset with `acorn` and filter it out on parse error. But why does this `haul` set `.bundle` extension for each asset? Does all these `.bundle` files contain pure JS code?

**Comment by Tvrqvoise** [comment]
Wrapping `acorn` in a `try / catch` seems messy and indirect, and my case is probably enough of an edge case that it's not worth adding that smell to your code base.  My mental model of this module was incorrect as well -- I'd assumed that this worked by recursively walking through the `stats.chunks` array, in which case it should be enough to just check for any chunks which are `"rendered": true`. Instead, it appears that you actually parse the output asset bundles themselves, which would be much more accurate and agnostic than my assumption, but also means that you have to assure that they're valid JavaScript.

All of this to say, I'm closing this ticket as it appears more user error than anything else.  Maybe if a bunch of other consumers start reporting similar issues it might be worth investigating more, but for now, I can just monkey patch it to work locally.
