### ISSUE TITLE
Missing `preact` dependency?

### ISSUE THREAD

**Issue by AviVahl** [webpack-contrib/webpack-bundle-analyzer#208]
#### Issue description
When installing v3.0.1, the following warning appears:
`warning "webpack-bundle-analyzer > mobx-preact@3.0.0" has unmet peer dependency "preact@>=8".`

#### Technical info
* Webpack Bundle Analyzer version: 3.0.1
* Webpack version: 4.18.0
* Node.js version: 8.12.0
* npm/yarn version: yarn 1.9.4
* OS: fedora 28

**Comment by valscion** [comment]
#209 will fix this
