### ISSUE TITLE
console.log in webpack.config.js ends up into stats.json

### ISSUE THREAD

**Issue by yvele** [webpack-contrib/webpack-bundle-analyzer#211]
If I have a `console.log` in my `webpack.config.js` then it will output in my `stats.json` 🤔 

I'm using

```
webpack --profile --json > stats.json
```

And it make sense I got all console logs.. That doesn't look like a bug.

But is there any workaround? Like [detecting `--profile`](https://stackoverflow.com/questions/44113359/passing-command-line-arguments-to-webpack-config-js) inside my `webpack.config.js` to do a conditional `console.log`?

If we found a clean workaround we maybe can add it to the docs

**Comment by yvele** [comment]
I mean if in my `webpack.config.js` any of my plugins make a `console.log`

```js
export default {
  plugins : [
    new NormalModuleReplacementPlugin(/^mysql2$/, (resource) => {
       console.log("LOL");
    }
  ]
}
```

I will have it in my `stats.json`:

```diff
+ LOL
{
  "errors": [
    "main.js from UglifyJs\nundefined"
  ],
  "warnings": [
    "..."
  ],
  "version": "4.19.1",
  "hash": "2dc6812ac9fe95561985",
  "time": 17174,
  "builtAt": 1537551342202,
  "publicPath": "",
  "outputPath": "/Users/yves/repo/dist",
  "assetsByChunkName": {
    "main": "main.js"
  }
}
```

**Comment by th0r** [comment]
That's how Linux works. It's neither analyzer nor webpack problem.

**Comment by yvele** [comment]
I know I'm talking about docs!

**Comment by valscion** [comment]
You might want to look at something like the [debug](https://www.npmjs.com/package/debug) package to only output console logs if an environment variable is set.

**Comment by goodwin64** [comment]
I've faced the same issue:
![image](https://user-images.githubusercontent.com/10671879/79682401-a06da900-822a-11ea-8185-0fe92e80c00a.png)


Didn't catch how to use the mentioned "debug" package. @valscion could you please clarify?

**Comment by valscion** [comment]
Sorry, I'm unable to provide debugging help regarding projects outside of webpack-bundle-analyzer code 😞
