### ISSUE TITLE
webserver keeps running after CTRL+C

### ISSUE THREAD

**Issue by coder82** [webpack-contrib/webpack-bundle-analyzer#218]
#### Issue description
The webserver serving the analysis page keeps running even when I stop webpack.

#### Technical info
* Webpack Bundle Analyzer version: 3.0.3
* Webpack version: 4
* Node.js version: 10
* npm/yarn version: 5
* OS: Windows 10

Then if I try to run the second time, of course the port is taken and the whole things doesn't run anymore.

**Comment by th0r** [comment]
Properly fill an issue template please.
