### ISSUE TITLE
Running Analyzer on remote dev server

### ISSUE THREAD

**Issue by crs1138** [webpack-contrib/webpack-bundle-analyzer#233]
#### Issue description
How do I make Webpack Bundle Analyzer to work on a remote dev server? I've tried following settings:
```
    new BundleAnalyzerPlugin({
      analyzerHost: 'http://mydev.server.com',
    }),
```
but I get following error:
```
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo ENOTFOUND http://mydev.server.com
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
```
Not sure, how to go about this.

#### Technical info
* Webpack Bundle Analyzer version: 3.0.3
* Webpack version: 4.16.3
* Node.js version: 9.4.0
* npm/yarn version: yarn 1.12.1
* OS: Debian Linux

#### Debug info
How do you use this module? As CLI utility or as plugin?
plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```
    new BundleAnalyzerPlugin({
      analyzerHost: 'http://mydev.server.com',
    }),
```
What other Webpack plugins were used?
```
    new webpack.ProgressPlugin(),
    new webpack.ProvidePlugin()
```
It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
`stats.json` will be created in Webpack bundle output directory.
[b47-stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/2657234/b47-stats.json.zip)

**Comment by valscion** [comment]
You probably need to set `analyzerHost` to `0.0.0.0` or some other, publically available IP on your dev server, while configuring DNS somewhere else to point `http://mydev.server.com` to your dev machine.

How to configure DNS to point to your dev server IP is out of scope of `webpack-bundle-analyzer`, though 😅

**Comment by valscion** [comment]
(I closed this issue as it seems to be a support case — I will reopen if this turns out to be a bug or something we could fix on our side)

**Comment by valscion** [comment]
Great! :relaxed: Let me know if you got it working — I haven't heard others using a separate development server with `webpack-bundle-analyzer` before, so I'm curious to know how it works.

**Comment by crs1138** [comment]
Yes, `0.0.0.0` works fine then I can access it using http://mydev.server.com:8888
