### ISSUE TITLE
Comment on #128

### ISSUE THREAD

**Issue by zwhitchcox** [webpack-contrib/webpack-bundle-analyzer#235]
So, I just want to add a comment referencing #128, which was closed

for me, the problem was I had `devtool` set to `"eval-source-map"`

Just posting this, because that was the top google result, if anyone else happens upon this.

**Comment by zwhitchcox** [comment]
Well, it's still not showing up, I guess because the issue is locked. Can someone unlock the issue so I can post the comment, and then it can go back to being locked again, I guess, or better yet just leave it unlocked

**Comment by valscion** [comment]
Can you please fill in the issue template?

**Comment by valscion** [comment]
Oh yes, now I know what you mean.

Would you be open to adding a new section to the Troubleshooting section in README.md? I can link to the PR adding the new docs in #128, as if #128 is the top google result, we should provide some way of documenting this gotcha.

You can take inspiration from https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/231

**Comment by valscion** [comment]
Let's continue discussion in https://github.com/webpack-contrib/webpack-bundle-analyzer/discussions/582
