### ISSUE TITLE
Angular CLI version 7 - can't see all the dependencies in a chunk

### ISSUE THREAD

**Issue by tomschreck** [webpack-contrib/webpack-bundle-analyzer#236]
#### Issue description
...
I'm using Angular CLI version 7.1.0 and am experiencing modules being concatenated: 

![image](https://user-images.githubusercontent.com/2521463/50020511-cf6f6d00-ff9b-11e8-89fa-6122b5722a3f.png)

Your troubleshooting section provides a solution for Angular CLI < 6.0.0.  Do you have a fix for Angular CLI 7 please?

Thanks for your time.

**Comment by th0r** [comment]
Open left sidebar and toggle corresponding checkbox.

**Comment by tomschreck** [comment]
@th0r thank you.  I've never noticed that before.

**Comment by valscion** [comment]
Hmm should we perhaps remove the "I can't see all the dependencies in a chunk" part in troubleshooting section @th0r now, as it is quite outdated?
