### ISSUE TITLE
Absolute Import for ES6 Modules `This dependency was not found:`

### ISSUE THREAD

**Issue by webberwang** [webpack-contrib/webpack-bundle-analyzer#240]
#### Issue description
Absolute import for ES6 modules throw error `This dependency was not found:`

#### Technical info
* Webpack Bundle Analyzer version: 3.0.3
* Webpack version: 4.28.4
* Node.js version: 10.0.0
* npm/yarn version: 1.12.3
* OS: macOS 10.14.2

More of a general question, there doesn't seem to be any settings to allow for absolute import to be resolved.

**Comment by webberwang** [comment]
@th0r like importing our own ES6 modules

`import MyComponent from 'src/MyComponent` instead of `import MyComponent from './src/MyComponent`.

I have 

```
resolve: {
  modules: []
}
```
set in Webpack as well

**Comment by th0r** [comment]
Who throws "This dependency was not found" error?

**Comment by webberwang** [comment]
@th0r My mistake! I did a reproduction with CRA absolute import & it seemed to be working, I'll re-open if I can isolate the issue.
