### ISSUE TITLE
Why is there a lodash in the package file?

### ISSUE THREAD

**Issue by mqliutie** [webpack-contrib/webpack-bundle-analyzer#249]
#### Issue description
![image](https://user-images.githubusercontent.com/11795518/52610732-55853280-2ebd-11e9-8652-24de92ab8845.png)

First I think I used modules import the lodash.
I opened the source code of lodash and add the console, but  the console is not print.
So, Is it wrong?
Should I do something to remove the lodash?

**Comment by valscion** [comment]
For some reason your bundle does contain lodash. I'm afraid we don't have the bandwidth to provide support to answer why your bundle has it.

**Comment by th0r** [comment]
@mqliutie you can run `npm ls --prod lodash` to show all the dependencies that use lodash. Seems like yoou have some of them in your bundled.

**Comment by mqliutie** [comment]
@th0r Thanks for you reply
