### ISSUE TITLE
Feature Request - Show boundaries of the file to help dig in further

### ISSUE THREAD

**Issue by PWKad** [webpack-contrib/webpack-bundle-analyzer#253]
#### Issue description
...

#### Technical info
* Webpack Bundle Analyzer version:
* Webpack version:
* Node.js version:
* npm/yarn version:
* OS:

#### Debug info
This is a feature request.  Currently when I dive in and see a file is 20kb for instance I can't get any further to see exactly how that is calculated.  I'm looking at the generated CSS file and the offending characters only appear to be about 5kb of that so I'm not entirely sure what all is included in the measurement (to know what to work on)

**Comment by PWKad** [comment]
BTW if this information is available or documented somewhere I think that would be sufficient as well to help in place of more features.

**Comment by th0r** [comment]
Fill issue template properly and provide a reproduction please.

**Comment by PWKad** [comment]
Was a feature request so template didn't apply and can't repro it :)  No worries though

**Comment by th0r** [comment]
If you mean you want to see the contents of the files/modules then I have this feature in mind for the future releases.

**Comment by PWKad** [comment]
Yeah exactly that's what I'm thinking is possibly clicking on the file at the lowest level gives you a view of exactly which files and their contents somehow to dig in and see if, for example, you have a line that imports a bunch of sourcemaps.
