### ISSUE TITLE
Allow hosting from different base url / homepage

### ISSUE THREAD

**Issue by MrHen** [webpack-contrib/webpack-bundle-analyzer#254]
#### Issue description
I need a way to prepend a specific url to both the root location and `viewer.js`. I am hosting the bundle viewer through a docker container and am running nginx to route various urls into the servers.

As best as I can tell, one of the the following changes would give me a way to do what I want:

* Change the link to `viewer.js` to prepend a base url setting: https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/views/viewer.ejs#L8
* Expose the `projectRoot` option for configuration: https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/src/viewer.js#L48

#### Technical info
* Webpack Bundle Analyzer version: `webpack-bundle-analyzer@3.1.0`
* Webpack version:
```
+-- react-scripts@2.1.8 
| `-- webpack@4.28.3 
```
* Node.js version: `v8.15.0`
* npm/yarn version: npm `6.4.1`
* OS: Docker

#### Debug info

CLI command:
```react-scripts build --stats && webpack-bundle-analyzer build/bundle-stats.json -m server -O --port 8888 --host 0.0.0.0```

nginx configuration:
```
upstream analyzer {
    server reporting-2-analyzer:8888;
}

server {
    # ...
    location /analyzer {
        proxy_pass http://analyzer;
    }

    # webpack-bundle-analyzer does not support a base url
    location /viewer.js {
        proxy_pass http://analyzer;
    }
```

**Comment by th0r** [comment]
@MrHen will usage of the relative url for `viewer.js` help? E.g.
```html
<script src="viewer.js"></script>
```

**Comment by MrHen** [comment]
Yeah, that would probably work.

**Comment by MrHen** [comment]
I confirmed the fix on my end. Thanks @th0r !
