### ISSUE TITLE
CHANGELOG.md #264 doesnt not exists

### ISSUE THREAD

**Issue by mercuriete** [webpack-contrib/webpack-bundle-analyzer#259]
Changelog is pointing to a non existent pull request.
https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/264

please fix the changelog.md

somewhere in 3.3.0 release:

https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/CHANGELOG.md#330

**Comment by th0r** [comment]
Fixed

**Comment by mercuriete** [comment]
Thanks for your work
:)
