### ISSUE TITLE
Feature Request: output the report.html to memoryfs when it is from webpack-dev-server

### ISSUE THREAD

**Issue by wood1986** [webpack-contrib/webpack-bundle-analyzer#270]
#### Issue description
Actually, this lib should not support "server" scenario because webpack-dev-server can do this for us. What you need is to output the report.html to the MemoryFS. It also solves #12

**Comment by valscion** [comment]
Can you expand a bit on why this is necessary? And what do you mean by "this lib should not support "server" scenario because webpack-dev-server can do this for us"

**Comment by wood1986** [comment]
@valscion, you can reuse the webpack-dev-server for the "server" scenario. Then you do not need to maintain the server and express

Before
![before](https://user-images.githubusercontent.com/5212215/56560558-9d79a300-6559-11e9-9e35-ec228ac24d2b.gif)

**Comment by wood1986** [comment]
After
![after](https://user-images.githubusercontent.com/5212215/56560856-6ce63900-655a-11e9-86d1-477d2a3c08d8.gif)

**Comment by valscion** [comment]
> One more thing, it will not generate anything when it is from webpack-dev-server

So does this change the current functionality in a backwards-incompatible way?

**Comment by wood1986** [comment]
@valscion I may need your help to tell me
* what the use cases of using `static` and `webpack-dev-server` together are?
* how do they use it for?

Because if it is a build pipeline, people will use `webpack` not `webpack-dev-server` and it still output report.html file. If it is a coding scenario, people will use `webpack-dev-server`. Unless people have some tasks after the compilation, for example, they watch the output of the report.html and then do something on change. I will doubt if this is the case because this kind of setup is not that easy relatively. I do not want to introduce a mode call "hybrid" for backward-compatible reason because it is a little bit overhead. So I do not know what the best approach is. 

| Before | server           | static  |
| ------------- |:-------------:|:-----:|
| webpack      | use express | output a file |
| webpack-dev-server      | use express |   output a file |


| After | server           | static  |
| ------------- |:-------------:|:-----:|
| webpack      | use express | output a file |
| webpack-dev-server      | use express |  no file output but output to memoryfs |

**Comment by valscion** [comment]
Thanks — I think I got it now. So your proposal is to change the `static` option when used with `webpack-dev-server` to output the file to memory so that it will be available in the existing dev server when user GETs the report by file path?

So in effect we'd add some behavior to the user's `webpack-dev-server` by making some special path output the bundle report instead of a 404 page?

**Comment by wood1986** [comment]
> So your proposal is to change the static option when used with webpack-dev-server to output the file to memory so that it will be available in the existing dev server when user GETs the report by file path?

You are correct!! The good thing is it solves the multi-compiler issue which is #12 

> So in effect we'd add some behavior to the user's webpack-dev-server by making some special path output the bundle report instead of a 404 page?

If you have a chance to review my PR, you do not need to do anything because of `this.compiler.outFileSystem`

Here is my suggestion for the rollout plan if you agree because it is a little bit aggressive. You can just directly introduce a breaking change and this change will remove `analyzerPort`, `analyzerHost`, `analyzerMode`, `openAnalyzer`. Of course the library no longer support a web server report.

**Comment by valscion** [comment]
> Of course, telling people the library no longer supports a web server report. If they want it, they need to use webpack-dev-server

This will most likely be a non-option, I'm afraid. We will likely need to support the web server report without requiring our users to install `webpack-dev-server`.



> If you have a chance to review my PR, you do not need to do anything because of `this.compiler.outFileSystem`

I don't really understand how `this.compiler.outFileSystem` works so that's why I'm still unsure what's happening there. Your PR currently also does this:

```js
outputFileSystem.writeFileSync = fs.writeFileSync.bind(outputFileSystem);
```

which feels like it's mutating something that was passed from outside, so I'm not sure what's happening there.

**Comment by wood1986** [comment]
Think about this, to generate a report from the plugin, people need to use `webpack`. As people use `webpack`, it is hard for me to believe they do not use `webpack-dev-server`. Maybe you can ask people how many of them will use "server" mode as I do not have a reputation on Twitter

The reason I add `outputFileSystem.writeFileSync = fs.writeFileSync.bind(outputFileSystem);` is [NodeOutputFileSystem.js](https://github.com/webpack/webpack/blob/master/lib/node/NodeOutputFileSystem.js) does not have `this.writeFileSync`

**Comment by valscion** [comment]
I know I use server mode sometimes to create a report that doesn't write to any file, even though my project doesn't use `webpack-dev-server` ¯\\\_(ツ)_/¯

Thanks for shedding light on this. I'm not sure how to proceed from here — I'll let @th0r also read this thread when he has time to figure out if this is something we want to act upon.

**Comment by wood1986** [comment]
Thanks for considering. I am happy to finalize my implementation. Just let me know

**Comment by th0r** [comment]
Thanks for the contribution, but I don't want to introduce breaking change and force people to install `webpack-dev-server` if they don't want to generate report files in filesystem.

**Comment by wood1986** [comment]
@th0r I hope you can reconsider the benefits such as fixing #12 and no need to maintain your express code. Maybe it is too much in the current release. If you have a chance to have a major release, please consider that.
