### ISSUE TITLE
feature request: please change default port

### ISSUE THREAD

**Issue by justnewbee** [webpack-contrib/webpack-bundle-analyzer#287]
i saw a closed issue here: https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/202

however, i still need to report this one..

this is a FEATURE REQUEST instead of an issue.

because seeing charles failing is very frustrating, and it takes quite quite a while for me do recall that i have come into this problem some time before.

changing the default port shall not affect anything, but will ease charles users' pain.

**Comment by th0r** [comment]
Why can't you use either `-p` CLI flag or `analyzerPort` config option?
