### ISSUE TITLE
Proposal: Group bundles by entry point and display aggregate statistics of selected bundles

### ISSUE THREAD

**Issue by avin-kavish** [webpack-contrib/webpack-bundle-analyzer#289]
I use the SplitChunkPlugin to optimize my bundles. Since it splits a single entry point over multiple bundles, the total stat, parsed and gzipped sizes are not that helpful for me. I'm more interested in the size per entry point. It would be nice to have per entry point sizes with the ability to group by entry point on the sidebar so that I can easily switch between them. Currently, I have to read through the list and tick each bundle individually that corresponds to the entry point I'm analysing. Then I have to use a calculator or do the mental math to see how big a single entry point is. It would be nice to see the following information at a glance.

 - Total size of options ticked on the sidebar
 - Option to group bundles by entry point
 - Display stat, parsed, gzipped size for each entry

**Comment by avin-kavish** [comment]
Any thoughts on this?

**Comment by valscion** [comment]
Sounds difficult. I have no idea how much work implementing and supporting this kind of feature would be

**Comment by avin-kavish** [comment]
Maybe as a start, I could do the first bullet point. Show the total of selected options.

**Comment by valscion** [comment]
Sure — would be nice to see what such an UI would look and feel like in practice.

**Comment by avin-kavish** [comment]
Initially I was thinking something like this:

![image](https://user-images.githubusercontent.com/48435155/62342922-4c892b80-b506-11e9-9f4d-9f905f1c9100.png)

Now that I read the other issue, I can update the total near "all" but that would require ticking all again to see the total losing the custom selection in the process..

**Comment by valscion** [comment]
The list of chunks might be quite long -- will people notice this total count if it's in the bottom?

Still, would be an improvement on the current UI

**Comment by pas-trop-de-zele** [comment]
Hi @valscion, I opened a PR which allows user to filter per entry point. Here’s the PR: #519

**Comment by valscion** [comment]
I'll close this issue as the original feature request seems done by https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/519
