### ISSUE TITLE
Webpack Bundle Analyzer 3.3.2 Takes >1min

### ISSUE THREAD

**Issue by pxwee5** [webpack-contrib/webpack-bundle-analyzer#294]
#### Issue description
generateStatsFile: true takes more than a minute, previously just seconds. 

#### Technical info
* Webpack Bundle Analyzer version: 3.3.2
* Webpack version: 4.36.1
* Node.js version: 10.16
* npm/yarn version: 6.9
* OS: Mac OS Mojave

#### Debug info
Used as a Plugin:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
**What other Webpack plugins were used?**
MiniCssExtractPlugin
ManifestPlugin
VueLoaderPlugin

**Comment by pxwee5** [comment]
Stats json uploaded.
[stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/3409333/stats.json.zip)

**Comment by th0r** [comment]
We won't be able to help without reproduction repo, sorry.

**Comment by pxwee5** [comment]
https://github.com/pxwee5/analyzer-test
Here you go. I've started a new repo with minimal code and the dependencies in the project. 

If you checkout first commit, `npm run build`, build time is around <10s.

If you checkout second commit
`rm -rf node_modules`
`npm install`
`npm run build` 
the build takes around 35s to complete.

**Comment by pxwee5** [comment]
**Additional Info:**
Funny part is this only happens when you install with `npm install`. If you use `yarn`, build time is normal. I'm super confused now.

**Comment by nolanlawson** [comment]
FWIW I've found that removing `generateStatsFile: true` usually greatly speeds up the time taken by WebpackBundleAnalyzer.

**Comment by valscion** [comment]
Oh true, `generateStatsFile` definitely impacts performance and can be left out to still get a usable report.

**Comment by th0r** [comment]
@pxwee5 could you try v4.1.0? Generation of `stats.json` should be much faster there.
