### ISSUE TITLE
[FR] All (Size) Should Recalculate Based On Checked Modules

### ISSUE THREAD

**Issue by pxwee5** [webpack-contrib/webpack-bundle-analyzer#295]
Just a feature request:

When checking only `vendor~main` and `vendor~form`, "All" should show `137.2KB`

![image](https://user-images.githubusercontent.com/14123790/61510967-36c93000-aa49-11e9-8593-4a4945de199f.png)

**Comment by valscion** [comment]
Sounds like https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/289#issuecomment-516416141, closing as duplicate
