### ISSUE TITLE
options is required for 3.4.0

### ISSUE THREAD

**Issue by crixusshen** [webpack-contrib/webpack-bundle-analyzer#300]
in the new 3.4.0,I found options of new BundleAnalyzerPlugin(options?: object) that it become required, otherwise it will get an error: Cannot use 'in' operator to search for 'analyzerPort' in undefined. if using the new BundleAnalyzerPlugin({}) in this way is successful.Is there a problem with 3.4.0？

**Comment by valscion** [comment]
Thanks, this seems like a regression caused by https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/290

We'll get a fix out shortly

**Comment by valscion** [comment]
Fixed in v3.4.1

**Comment by avin-kavish** [comment]
2 years working with javascript and never knew the `in` operator didn't work on undefined. All the tests passed too.

**Comment by valscion** [comment]
Passing null as options has never been supported

**Comment by th0r** [comment]
> Passing null as options has never been supported.

Yes, we shouldn't cover this case - it's a user's responsibility to provide parameter with proper type.
