### ISSUE TITLE
[Bug] Sidebar didn't show correct chunks when fixing.

### ISSUE THREAD

**Issue by gaokun** [webpack-contrib/webpack-bundle-analyzer#316]
#### Issue description
Fix the sidebar, then hide `app.js`, we can still see it as checked in sidebar.

![image](https://user-images.githubusercontent.com/7044628/65409084-6b76b080-de19-11e9-9e96-0af8021a60bc.png)

#### Technical info
- Webpack Bundle Analyzer version: 3.5.0
- Webpack version: 4.39.3
- Node.js version: 10.15.3
- npm/yarn version: 6.11.3
- OS: MacOS

**Comment by valscion** [comment]
Did you hide the `app.js` it via the popup menu or how?

**Comment by gaokun** [comment]
Yes, hide it via contextmenu.

I found this bug when I try to make a gif for PR #315 

Here is the gif: 

> I used contextmenu to hide app.js

![webpack-bundle-analyzer](https://user-images.githubusercontent.com/7044628/65404862-d79ee780-de0c-11e9-9238-d6ab1301ba47.gif)

**Comment by bregenspan** [comment]
@valscion yes, I can take a look at this!

**Comment by valscion** [comment]
Fix is available in release v3.5.2 :tada:
