### ISSUE TITLE
Tile texts are way too big on Brave

### ISSUE THREAD

**Issue by ValentinH** [webpack-contrib/webpack-bundle-analyzer#318]
#### Issue description
When opening the treemap on Brave, here's what I get:
![image](https://user-images.githubusercontent.com/2678610/65582399-a09c1380-df7d-11e9-87f5-f241a786c759.png)

While on Chrome, everything's fine:
![image](https://user-images.githubusercontent.com/2678610/65582489-cde8c180-df7d-11e9-91c4-8bcdcb0bee1d.png)

This is really weird as Brave is a Chromium based browser. 🤔 I've also tried opening in "Private" mode to ensure it was not due to an extension...

#### Technical info
* Webpack Bundle Analyzer version: 3.5.1
* Webpack version: 4.29.6
* Node.js version: 10.15
* npm/yarn version: yarn 1.16
* OS: MacOS 10.14.6
* Browser: Brave Version 0.68.138 Chromium: 77.0.3865.75

#### Debug info
I use the webpack plugin without any option.

**Comment by th0r** [comment]
I think you should send a bug report to the Brave team as this treemap works fine in all major browsers.

**Comment by valscion** [comment]
Do any of these FoamTree demos perhaps look strange in Brave? https://get.carrotsearch.com/foamtree/latest/demos/

**Comment by ValentinH** [comment]
@valscion surprisingly, all demos are fine! 🤔

**Comment by valscion** [comment]
I wonder if we are running on an older version of FoamTree, then? Might be worth checking that possibility out

**Comment by ValentinH** [comment]
Indeed, webpack-bundle-analyzer is using version 3.4.5 while the latest is 3.4.9.

**Comment by valscion** [comment]
Can you try figuring out a way to update foamtree? I don't remember how to do it 😅

**Comment by th0r** [comment]
Just copy-paste it into the repo 😉

**Comment by ValentinH** [comment]
OK I'll try it and open a PR if it works 🙂

**Comment by ValentinH** [comment]
I've just tried using the latest version (taken from the demo) and I still have the same issue.

**Comment by valscion** [comment]
Ach, then there's nothing we can do, sorry.

**Comment by ValentinH** [comment]
I understand, thank you for the answers 🙂

**Comment by th0r** [comment]
@ValentinH I would suggest opening an issue in the Brave repo.

**Comment by ValentinH** [comment]
I understand, thank you for the answers 🙂

**Comment by tegdtna** [comment]
Also using Brave. 
Just wanted to note that if I go to http://localhost:8888/ instead of http://127.0.0.1:8888/ the issue seems to go away. Once I added the `-h localhost` host option, the tool worked as expected.

**Comment by danlaush** [comment]
Thanks @tegdtna, that worked for me. Such a strange issue and mysterious fix.

**Comment by cpboyd** [comment]
The issue seems to be related to setting "Block fingerprinting" to Strict. Further, I still see it when using localhost and rendering a local file.
