### ISSUE TITLE
Add a non-default option to open the report with "Show content of concatenated modules" already enabled

### ISSUE THREAD

**Issue by lorenzos** [webpack-contrib/webpack-bundle-analyzer#321]
Webpack does concatenate nearly all my source modules (React components), therefore I always need to open the sidebar and check "Show content of concatenated modules" when analyzing my bundles.

I see there are [good reason to not enable it by default](https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/188), but it'd be great to have an opt-in flag in the options object to open the report with concatenated modules already shown.

**Comment by valscion** [comment]
Hmm I'm not sure if that's worth the cost added by a new option and maintenance burden. I think it should always be an informed choice to show inaccurate information, so not adding it as an option would force people to always understand that the information they're seeing is indeed inaccurate.

The people writing the configuration can be different people to those who view the analysis, and that I'm worried about.

What do you think, @th0r?

**Comment by th0r** [comment]
@valscion I wonder, maybe we can store such settings in `localStorage`? Won't it solve your problem @lorenzos?

**Comment by valscion** [comment]
It could — that way the UI would remember your choice but you would've been the one to make that choice in the first place, not the one who wrote the configuration.

**Comment by lorenzos** [comment]
@th0r Sure, it'll be ok for my use case.

**Comment by valscion** [comment]
A PR to implement such `localStorage` option is welcome ☺️
