### ISSUE TITLE
after Webpack Bundle Analyzer version 3.0.3 ，this plugin don't support Microsoft Edge Browser

### ISSUE THREAD

**Issue by inier** [webpack-contrib/webpack-bundle-analyzer#329]
#### Issue description
after Webpack Bundle Analyzer version 3.0.3 ，this plugin don't support Microsoft Edge Browser.

#### Technical info
* Webpack Bundle Analyzer version: 3.6.0
* Webpack version: 4.41.2
* Node.js version:10
* npm/yarn version:1.19.2
* OS:window

#### Debug info
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

**Comment by valscion** [comment]
Huh. Would you be able to debug further in Microsoft Edge to find out which piece of code throws the error you're seeing, and maybe post a screenshot?

**Comment by th0r** [comment]
@inier yes, [it doesn't](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/.browserslistrc). Reasoning for this was that it's a developer tool and I decided that most popular evergreen browsers is enough. Why do you need Edge support?

**Comment by th0r** [comment]
Closed due to inactivity.
