### ISSUE TITLE
Does not show correct size.

### ISSUE THREAD

**Issue by Ciavarella** [webpack-contrib/webpack-bundle-analyzer#331]
#### Issue description
Hi!

I apologise in advance if this is the wrong forum.

Im having trouble getting the full size of the bundle. When i check the dist folder that webpack outputs it it huge, 121.7 mb. When i check the webpack-bundle-analyzer it shows:
Stat: All: (20.9 MB)
Parsed: All (9.48 MB)
Gzipped: All (2.67 MB)

Can this really be correct? I create a stats.json file in the dist folder that is outputted by webpack.

The dist directory layout is:
* dist
   */css
   */fonts
   */img
   */js

I can't be seem to be able to see the whole dist folder with stats.json.

#### Technical info
* Webpack Bundle Analyzer version: "^3.6.0"
* Webpack version: "^4.31.0"
* Node.js version: v12.12.0
* npm/yarn version: npm: 6.11.3
* OS: macOS Catalina (10.15.2)

#### Debug info
How do you use this module? As CLI utility or as plugin?

As plugin:
config
    .plugin("webpack-bundle-analyzer")
    .use(BundleAnalyzerPlugin)
    .init(Plugin => new Plugin({
      analyzerMode: 'disabled',
      generateStatsFile: true,
      statsOptions: { source: 'verbose' }
    }));

What other Webpack plugins were used?

It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
`stats.json` will be created in Webpack bundle output directory.

**Comment by valscion** [comment]
`webpack-bundle-analyzer` does not show you the sizes of your assets (like css, fonts, images), only size of your output JS code

**Comment by Ciavarella** [comment]
> `webpack-bundle-analyzer` does not show you the sizes of your assets (like css, fonts, images), only size of your output JS code

Ah i understand. Still the JS folder is 43,3 MB in the dist folder. So half of the outputted folder.

**Comment by valscion** [comment]
Strange. I'm afraid we can't debug this unless you're able to create a minimal reproduction case of this issue.

Does the JS folder contain your stats.json file? It might be the culprit, as it might contain your original source code in it.

**Comment by Ciavarella** [comment]
I understand.

The stats.json file is not inside the JS folder, it is outside directly in the dist folder.

**Comment by valscion** [comment]
Maybe the dist folder contains something that won't be included in your runtime code? The way `webpack-bundle-analyzer` works is it checks what output JS files you have by reading from the webpack stats object — basically, using the same data as is present in the `stats.json` file.

Then `webpack-bundle-analyzer` reads those output files from the disk, parses them and rebuilds the module contents to analyze what was in the bundles themselves.

So even if `dist/` folder has more data in it, it might not be shipped to the user. Are you sure all the files inside your `dist/js/` are JavaScript output files that will at some point be sent to the user at all? There could be duplicate output files, for example if you ship different files to different users. Or there might be sourcemap files, which are not taken into account when calculating the bundle sizes as they are not imported by webpack when running your code in the browser.

**Comment by Ciavarella** [comment]
Okey, the /js folder has .js files and .js.map files.

I need to look in to it if all the files will be sent to the user.

Thank you for all your help!
