### ISSUE TITLE
Compiling Vue using modern mode causes an 'address in use' error when doing the second build.

### ISSUE THREAD

**Issue by shadow7412** [webpack-contrib/webpack-bundle-analyzer#332]
#### Issue description
The --modern flag in Vue allows you to build two projects - one with all of the necessary polyfills to allow older browsers to use your app, and a modern bundle which lacks then as well as various transpiling that modern browsers do not need.

This gives us the benefit of maintaining browser compatibility, but also slimming down the packages sometimes considerably for browsers that support certain features natively.

#### Technical info
* Webpack Bundle Analyzer version: 3.6.0
* Webpack version: 4.41.3
* Node.js version: 12.14.1
* npm version: 6.13.4
* OS: Windows 10

#### Debug info
How do you use this module? As CLI utility or as plugin?
Plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)
npx vue-cli-service build --modern src/main.js

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
No arguments.

What other Webpack plugins were used?
None

It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
`stats.json` will be created in Webpack bundle output directory.

It's worth noting that the modern build overwrote the stats.json created in the legacy build. I've captured both by quickly copying the stats file before it got overwritten. I do not suspect these will be relevant though, as it doesn't seem like an issue specific to my project.

[stats.json.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/4227657/stats.json.txt)
[stats-legacy.json.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/4227659/stats-legacy.json.txt)

**Comment by shadow7412** [comment]
Using the analyzerPort option works around this issue.

Example:
```
new BundleAnalyzerPlugin({
    analyzerPort: 'auto',
}),
```

**Comment by valscion** [comment]
Yeah looks like configuration for this is indeed present, so I'll close this issue.

**Comment by shadow7412** [comment]
I'd call this configuration a work-around rather than a fix... wouldn't `auto` be a much more sensible default for this option?

That way it won't clash with a common dev port and works as expected in situations like this...

**Comment by valscion** [comment]
Maybe. Changing a default could break some user's workflows so we won't be doing that unless we have a big reason otherwise.
