### ISSUE TITLE
Need an appropriate loader to handle this file type error

### ISSUE THREAD

**Issue by rupeshdabbir** [webpack-contrib/webpack-bundle-analyzer#336]
#### Issue description
I'm new to webpack and I'm trying to install Webpack Bundle Analyzer on my project and I'm getting this error after running `node_modules/.bin/webpack --profile --json`

I'm following this guide: https://www.codementor.io/@drewpowers/high-performance-webpack-config-for-front-end-delivery-90sqic1qa#7-webpack-bundle-analyzer

I've posted a stackoverflow query as well but no luck: https://stackoverflow.com/questions/60503018/webpack-bundle-analyzer-need-an-appropriate-loader-to-handle-this-file-type-err

Not sure if this is related to the library or am i missing something?

**Error:**
```
C02ZD1HBLVDR user$ node_modules/.bin/webpack --profile --json

{
  "errors": [
    "./src/index.js 47:2\nModule parse failed: Unexpected token (47:2)\nYou may need an appropriate loader to handle this file type.\n| \n| ReactDOM.render(\n>   <Provider store={store}>\n|     <MCApolloProvider>\n|       <AuthWrapper>"
  ],
  "warnings": [
    "configuration\nThe 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.\nYou can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/"
  ],
  "version": "4.19.1",
  "hash": "9574a566eab3b6564571",
  "time": 84,
  "builtAt": 1583223758357,
  "publicPath": "",
```

**index.js**

```
import { Provider } from 'react-redux';
import MCApolloProvider from '@src/shared/contexts/apollo-context';

ReactDOM.render(
  <Provider store={store}>
    <MCApolloProvider>
      <AuthWrapper>
        <SocketProvider>
          <FeatureFlagsProvider>
            <SPFProvider config={SPF_CONFIG}>
              <App />
            </SPFProvider>
          </FeatureFlagsProvider>
        </SocketProvider>
      </AuthWrapper>
    </MCApolloProvider>
  </Provider>,
  document.getElementById('root') || document.createElement('div'), // for testing
);
```

#### Technical info
* Webpack Bundle Analyzer version:^3.6.0
* Webpack version: 4.19.1
* Node.js version: v10.18.1
* npm/yarn version:6.13.4
* OS: MacOSX

#### Debug info
I've posted my package.json, webpack-dev config here:

https://stackoverflow.com/questions/60503018/webpack-bundle-analyzer-need-an-appropriate-loader-to-handle-this-file-type-err

**Comment by rupeshdabbir** [comment]
Please kindly help, I'm unable to use this bundle analyzer because of this error.

**Comment by th0r** [comment]
Sorry, but this issue doesn't have anything to do with bundle analyzer plugin. According to your `Unexpected token` error it seems like you haven't included `@babel/preset-react` into your babel config so webpack can't understand JSX syntax.
