### ISSUE TITLE
#No Bundles Parsed#

### ISSUE THREAD

**Issue by Romicodes** [webpack-contrib/webpack-bundle-analyzer#340]
#### Issue description
...
@valscion 
**Getting the following error message when trying to create a npm run build**

```
No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 4968172b96b83b06dca5
Version: webpack 4.42.0
Time: 58ms
Built at: 03/16/2020 4:48:31 PM

ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\Users\romibabe\documents\firefox**********************
```

#### Technical info

* Webpack Bundle Analyzer version: 3.6.1
* Webpack version: 4
* Node.js version: 12.6.1
* npm/yarn version:
* OS: Windows

#### Debug info

How do you use this module? As CLI utility or as plugin? **Plugin**

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)  

```
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
module.exports = {
  plugins: [
    new BundleAnalyzerPlugin()
  ]
}
```

What other Webpack plugins were used?

```
"webpack": "^4",
    "webpack-bundle-analyzer": "^3.6.1",
    "webpack-cli": "^3",
    "webpack-dev-server": "^3"
```

It would be nice to also attach webpack stats file.
It can be generated using these options:

```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```

`stats.json` will be created in Webpack bundle output directory.

**Comment by valscion** [comment]
Hi, thanks for opening the issue.

This part of the command output seems interesting:

```
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.
```

It seems like webpack itself is unable to generate your bundle. When webpack fails to generate a bundle, `webpack-bundle-analyzer` won't have output files to read the bundle contents from.

**Comment by Romicodes** [comment]
Thank you @valscion  for your feedback. I did manage to fix some of these issues and make some progress . Now the compile is successful but am only able to get stats file at the location pointed. 

 platform-health-dashboard@0.0.1 start C:\Users\romibabe\documents\f********
 webpack-dev-server --mode development

 ｢wds｣: Project is running at http://localhost:8080/
 ｢wds｣: webpack output is served from /
 ｢wds｣: Content not from webpack is served from C:\Users\romibabe\documents\firefox-health-dashboard
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
 ｢wdm｣: Hash: 6390aba674ba8ddc6d49
Version: webpack 4.42.0
Time: 607ms
Built at: 03/17/2020 10:15:45 PM
 Asset     Size  Chunks             Chunk Names
Main.js  363 KiB    main  [emitted]  main
ntrypoint main = main.js
0] multi (webpack)-dev-server/client?http://localhost:8080 ./src 40 bytes {main} [built]
./node_modules/ansi-html/index.js] C:/Users/romibabe/Documents/f****/node_modules/ansi-html/index.js 4.16 KiB {main} [built]
./node_modules/html-entities/index.js] C:/Users/romibabe/Documents/f*****/node_modules/html-entities/index.js 231 bytes {main} [built]
./node_modules/loglevel/lib/loglevel.js] C:/Users/romibabe/Documents/f******/node_modules/loglevel/lib/loglevel.js 8.41 KiB {main} [built]
./node_modules/url/url.js] C:/Users/romibabe/Documents/f*****/node_modules/url/url.js 22.8 KiB {main} [built]
./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
./src/index.js] 29 bytes {main} [built]
   + 18 hidden modules
 ｢wdm｣: Compiled successfully.

**Comment by Romicodes** [comment]
Hello @valscion ,  Thank you for your feedback! I did make a couple of changes ,end up  with a successful compile and the following, but still no parsed files? 


$ npm run start

> platform-health-dashboard@0.0.1 start C:\Users\romibabe\docu
> webpack-dev-server --mode development

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\romi
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
i ｢wdm｣: Hash: 7d4f68754733837952ff
Version: webpack 4.42.0
Time: 536ms
Built at: 03/17/2020 11:12:10 PM
  Asset     Size  Chunks             Chunk Names
main.js  363 KiB    main  [emitted]  main
Entrypoint main = main.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./
[./node_modules/ansi-html/index.js] C:/Users/romibabe/Document
[./node_modules/html-entities/index.js] C:/Users/romibabe/Docu
[./node_modules/loglevel/lib/loglevel.js] C:/Users/romibabe/Do
[./node_modules/url/url.js] C:/Users/romibabe/Documents/firefo
[./node_modules/webpack-dev-server/client/index.js?http://loca
[./node_modules/webpack-dev-server/client/overlay.js] (webpack
[./node_modules/webpack-dev-server/client/socket.js] (webpack)
[./node_modules/webpack-dev-server/client/utils/createSocketUr
[./node_modules/webpack-dev-server/client/utils/log.js] (webpa
[./node_modules/webpack-dev-server/client/utils/reloadApp.js]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js
[./node_modules/webpack-dev-server/node_modules/strip-ansi/ind
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync
./src/index.js] 29 bytes {main} [built]
   + 18 hidden modules
 ｢wdm｣: Compiled successfully.

**Comment by th0r** [comment]
Read Troubleshooting section of the readme please.

**Comment by valscion** [comment]
th0r is referencing this section: https://github.com/webpack-contrib/webpack-bundle-analyzer#i-dont-see-gzip-or-parsed-sizes-it-only-shows-stat-size

Looks like you're using `webpack-dev-server`. That's why you don't have bundles to parse, as no files are emitted. See the readme, https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/191 and https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/147 for example.

**Comment by HAOFUYANG** [comment]
When I used npm scripts to build my Vue 2 project, the JavaScript files in the 'dist' directory were not minified, and remained at their original size，only stat，not have parsed and gzip
