### ISSUE TITLE
How to get parsed size of every stats.modules

### ISSUE THREAD

**Issue by DremyGit** [webpack-contrib/webpack-bundle-analyzer#342]
#### Issue description

There is only stats size data in `stats.json`. I found `window.chartData` contains `parsedSize` and `gzipSize`  in `report.html`.But It\'s a tree so that I can\'t use them easily.

How can I get parsed size of every `stats.modules` directly without parse `report.html`? Could it be generated by the plugin with any options?

**Comment by valscion** [comment]
Soon, see https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/341
