### ISSUE TITLE
Inaccurate modules and total size

### ISSUE THREAD

**Issue by OZZlE** [webpack-contrib/webpack-bundle-analyzer#343]
#### Issue description
It reports lodash 133KB but it is only required by Babel which is not a part of the generated bundle. I tried moving all Babel modules to to requireDev but that didn't make any difference.

Total size says 1.78 MB but webpack says 1.22 MB.

#### Technical info
* Webpack Bundle Analyzer version: 3.7.0
* Webpack version: 3.12.0
* Node.js version: 12.4.0
* npm/yarn version: npm 6.9.0
* OS: MacOs Catalina

#### Debug info
    npm run webpack:profile > stats.json # builds a production bundle ( webpack -p --profile --json )
    sed -e '1,3d' < stats.json > tmp.json
    mv tmp.json stats.json
    webpack-bundle-analyzer stats.json

What other Webpack plugins were used?: None that I know of.

**Comment by th0r** [comment]
I can't help you without `stats.json` file.

> but webpack says 1.22 MB

What do you mean by `webpack says`?

> sed -e '1,3d' < stats.json > tmp.json

Why do you need this line?

**Comment by OZZlE** [comment]
> I can't help you without `stats.json` file.
> 
> > but webpack says 1.22 MB
> 
> What do you mean by `webpack says`?

    $ npm run webpack -p --profile --json analyzerMode=0 generateStatsFile=1 statsOptions={source:false}

                                          react-frontend.js    1.22 MB      10  [emitted]  [big]  main


> > sed -e '1,3d' < stats.json > tmp.json
> 
> Why do you need this line?

Otherwise this is added in the begining of the json file:
     > react-frontend@1.0.1 webpack /../react-frontend
     > webpack "analyzerMode=0" "generateStatsFile=1" "statsOptions={source:false}"

I'm struggling to create the stats.json file without sensitive data.. Haven't found a description of how to run in CLI, doing:

    npm run webpack -p --profile --json analyzerMode=0 generateStatsFile=1 statsOptions={source:false}

But then I get:

    ERROR in Entry module not found: Error: Can't resolve '0' in '/../react-frontend'

    ERROR in Entry module not found: Error: Can't resolve '1' in '/../react-frontend'

    ERROR in Entry module not found: Error: Can't resolve '{source:false}' in '../react-frontend'

**Comment by OZZlE** [comment]
@th0r by inspecting the stats.json file I can now see that lodash seems to be coming from `react-image-gallery` :) would be cool if this could be present in the UI also :) Thanks anyway :)

**Comment by th0r** [comment]
Yes, I have this feature in the roadmap.
