### ISSUE TITLE
Using WebWorkerChunkTemplatePlugin generates modules in an unrecognized way

### ISSUE THREAD

**Issue by Gongreg** [webpack-contrib/webpack-bundle-analyzer#351]
#### Issue description

While working using webpack for web-worker with chunks [WebWorkerChunkTemplatePlugin](https://github.com/webpack/webpack/blob/c9d4ff7b054fc581c96ce0e53432d44f9dd8ca72/lib/webworker/WebWorkerChunkTemplatePlugin.js) The source is created in this format:

```javascript
source.add(
	`${globalObject}[${JSON.stringify(
		chunkCallbackName
	)}](${JSON.stringify(chunk.ids)},`
);
```

So:
```javascript
self["chunkCallbackName"]([9],{
```

or
```javascript
self.chunkCallbackName([9],{ 
```
when the code is minified.

There should be a check for this.

**Comment by valscion** [comment]
PR is welcome :relaxed:
