### ISSUE TITLE
`analyzerMode: 'static'` doesn't seem to be working anymore.

### ISSUE THREAD

**Issue by yursha** [webpack-contrib/webpack-bundle-analyzer#356]
#### Issue description

`analyzerMode: 'static'` doesn't seem to be working anymore. No report file is generated and the web server is started.

#### Technical info
* Webpack Bundle Analyzer version: 3.8.0
* Webpack version: 4.43.0
* Node.js version: 14.0.0
* npm/yarn version: 16.14.5
* OS: Ubuntu 19.10

#### Debug info
How do you use this module? As CLI utility or as plugin?

Plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

`new BundleAnalyzerPlugin({ analyzerMode: 'static'})`

What other Webpack plugins were used?

- CleanWebpackPlugin
- HtmlWebpackPlugin
- Dotenv

It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
`stats.json` will be created in Webpack bundle output directory.

**Comment by valscion** [comment]
Can you test which earlier version of `webpack-bundle-analyzer` does work for you?

**Comment by hbobenicio** [comment]
Same issue here. Downgrading to 3.7 and 3.6 didn't work either.
I'm running the build with webpack-dev-server.

After some debugging, I don't know it this is a regression issue but what I saw is this:

[viewer.js](https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/src/viewer.js#L167)
```javascript
          fs.writeFileSync(reportFilepath, reportHtml);
```

I think this is not supposed to work with webpack-dev-server, right?
Is webpack-bundle-analyzer only emitting files with the fs module?
Isn't it a webpack plugin api for emitting files to the output directory? (for loaders, I known at least there is [this.emitFile](https://github.com/webpack-contrib/file-loader/blob/25e2668f75ae3e8f78adeb99297caa258b2479f3/src/index.js#L57))
I'm using webpack-bundle-analyzer as a plugin like this:

```
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

const webpackConfig = {
    //...
    plugins: [
        //...
        new BundleAnalyzerPlugin({
          analyzerMode: 'static',
          openAnalyzer: false,
        }),
    ]
}
```

So the question is:
- Can this plugin work with webpack-dev-server (with ram files) or only with webpack cli?
- If it can, then how? Am I missing docs with specific instructions somewhere?

**Comment by th0r** [comment]
> * Can this plugin work with webpack-dev-server (with ram files) or only with webpack cli?

No, it can't work with WBA (virtual file system).

**Comment by th0r** [comment]
@yursha does this issue still valid? I so, could you please create a reproduction repo.

**Comment by Jess3242** [comment]
> #### Issue description
> 
> 
> 
> `analyzerMode: 'static'` doesn't seem to be working anymore. No report file is generated and the web server is started.
> 
> 
> 
> #### Technical info
> 
> * Webpack Bundle Analyzer version: 3.8.0
> 
> * Webpack version: 4.43.0
> 
> * Node.js version: 14.0.0
> 
> * npm/yarn version: 16.14.5
> 
> * OS: Ubuntu 19.10
> 
> 
> 
> #### Debug info
> 
> How do you use this module? As CLI utility or as plugin?
> 
> 
> 
> Plugin
> 
> 
> 
> If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)
> 
> 
> 
> If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
> 
> 
> 
> `new BundleAnalyzerPlugin({ analyzerMode: 'static'})`
> 
> 
> 
> What other Webpack plugins were used?
> 
> 
> 
> - CleanWebpackPlugin
> 
> - HtmlWebpackPlugin
> 
> - Dotenv
> 
> 
> 
> It would be nice to also attach webpack stats file.
> 
> It can be generated using these options:
> 
> ```js
> 
> new BundleAnalyzerPlugin({
> 
>   analyzerMode: 'disabled',
> 
>   generateStatsFile: true,
> 
>   // Excludes module sources from stats file so there won't be any sensitive data
> 
>   statsOptions: { source: false }
> 
> })
> 
> ```
> 
> `stats.json` will be created in Webpack bundle output directory.
> 
>

**Comment by valscion** [comment]
Closing as there hasn't been a reproduction.
