### ISSUE TITLE
Migrate to kleur for colored prompts

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack-contrib/webpack-bundle-analyzer#359]
#### Issue description
[kleur](https://github.com/lukeed/kleur) is a lightweight alternative to [chalk](https://github.com/chalk/chalk). IMO it would be a good idea to migrate taking into account the bundle (install) size.

**Comment by jamesgeorge007** [comment]
@valscion thoughts?

**Comment by th0r** [comment]
What will be the difference in size between `chalk` and `kleur`?

**Comment by jamesgeorge007** [comment]
Results from `packagephobia`:
[chalk](https://packagephobia.com/result?p=chalk)
[kleur](https://packagephobia.com/result?p=kleur)

**Comment by th0r** [comment]
The thing is `chalk` is a quite popular package and there is a good chance that a project that uses `webpack-bundle-analyzer` also already uses some other package that depends on `chalk` and it won't be installed again (physically) - it will be just hoisted to the top level of the `node_modules` directory.

**Comment by jamesgeorge007** [comment]
Good point, closing.
