### ISSUE TITLE
Standardization of installation description

### ISSUE THREAD

**Issue by sarkiroka** [webpack-contrib/webpack-bundle-analyzer#363]
#### Issue description
Please use uniformly longer or shorter syntax uniformly in documentation to add this dependency to your project.

#### Technical info
I created a pull request, to make the documentation uniform, but it dropped out with comment: "we prefer the longer form". (https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/360) But the yarn syntax still use shorter form.

So, my proposal is use uniformly longer, or uniformly shorter syntax all of both case in readme documentation
```
# NPM
npm install --save-dev webpack-bundle-analyzer
# Yarn
yarn add --dev webpack-bundle-analyzer
```
or use the shorter form uniformly (I think, this is much better)
```
# NPM
npm i -D webpack-bundle-analyzer
# Yarn
yarn add -D webpack-bundle-analyzer
```
otherwise I think it is a discrimination.

I know it's just a very little thing but order is the soul of everything

**Comment by th0r** [comment]
> otherwise I think it is a discrimination

Sorry, but discrimination of who?

**Comment by sarkiroka** [comment]
of npm users who like shorter syntax, or anybody who wants to typing less. The point is not this, but the syntax above.

but abuse this part of sentence is a professional argument? I accept when you not agree pull request from the world. I accept when you more prefer yarn instead of npm. But I not accept the double standard, the judgment of one thing varies depending on who says it.
