### ISSUE TITLE
Lodash dependency causes prototype pollution issue: can you use another package instead of lodash?

### ISSUE THREAD

**Issue by marcoippolito** [webpack-contrib/webpack-bundle-analyzer#364]
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > webpack-bundle-analyzer > lodash          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523                            │
└───────────────┴────────────────────────────────────────

https://www.npmjs.com/advisories/1523

"No fix is currently available. Consider using an alternative package until a fix is made available."

So... can you use another package instead of lodash?

Marco

**Comment by valscion** [comment]
This vulnerability does not concern `webpack-bundle-analyzer`. Unfortunately we do not have the bandwidth to replace lodash from this package.
