### ISSUE TITLE
cannot add plugin to vue setup file

### ISSUE THREAD

**Issue by nicolasvahidzein** [webpack-contrib/webpack-bundle-analyzer#365]
Hello,

when i try to add the plugin code to my vue.config.js file it says plugins are not allow:

Invalid options in vue.config.js: "plugins" is not allowed

**Comment by nicolasvahidzein** [comment]
ok so i was able to find a couple of pointers, but i still get this error:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle merlin-admin-frontend@0.1.0~predev: merlin-admin-frontend@0.1.0
6 info lifecycle merlin-admin-frontend@0.1.0~dev: merlin-admin-frontend@0.1.0
7 verbose lifecycle merlin-admin-frontend@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle merlin-admin-frontend@0.1.0~dev: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\WebServer\ZeinTekWebServices\liveroot\merlin-admin-frontend\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Redis\;C:\Bitnami\WAMPstack\7.3.7-0\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\CMake\bin;C:\Program Files (x86)\curl\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Python\3.6;C:\Python\3.6\Scripts;C:\Program Files\nodejs;C:\Bitnami\WAMPstack\7.3.7-0\mysql\bin;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox;C:\Program Files\Docker Toolbox;C:\Program Files\Docker Toolbox;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle merlin-admin-frontend@0.1.0~dev: CWD: D:\WebServer\ZeinTekWebServices\liveroot\merlin-admin-frontend
10 silly lifecycle merlin-admin-frontend@0.1.0~dev: Args: [ '/d /s /c', 'vue-cli-service serve --host 192.168.2.5 --port 8018' ]
11 silly lifecycle merlin-admin-frontend@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle merlin-admin-frontend@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: merlin-admin-frontend@0.1.0 dev: `vue-cli-service serve --host 192.168.2.5 --port 8018`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid merlin-admin-frontend@0.1.0
15 verbose cwd D:\WebServer\ZeinTekWebServices\liveroot\merlin-admin-frontend
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.8.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error merlin-admin-frontend@0.1.0 dev: `vue-cli-service serve --host 192.168.2.5 --port 8018`
22 error Exit status 1
23 error Failed at the merlin-admin-frontend@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
const path = require("path");
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

module.exports = {
	
	devServer: {
		host: '192.168.2.5',
		port: '8018',
		public: '192.168.2.5:8018',
	},
	
	lintOnSave: false,
	
	runtimeCompiler: true,
	
	css: {
		modules: true
	},
	
	configureWebpack: {
		
		resolve: {
			
			plugins: [
				new BundleAnalyzerPlugin()
			],
			
			extensions: ['.js', '.vue', '.json', 'scss', 'css'],
			
			alias: {
				"Components": path.join(__dirname, 'src/components'),
				"Packages": path.join(__dirname, 'src/packages'),
				"CSSPackages": path.join(__dirname, 'src/packages/css'),
				"Styles": path.join(__dirname, 'src/packages/css/styles')
			}
			
		}
		
	}
	
}
```

**Comment by th0r** [comment]
Open an issue in a `vue-cli` repo please.
