### ISSUE TITLE
webpack-bundle-analyzer displays a blank page when run from the CLI

### ISSUE THREAD

**Issue by divmgl** [webpack-contrib/webpack-bundle-analyzer#367]
#### Issue description
Hello. When using the plugin the bundle analyzer displays everything correctly. However, I want to use a `stats.json` file that I'm generating with production flags on.

Unfortunately, the page is just completely blank.

#### Technical info

<pre>
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 201.30 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  npmPackages:
    koa-webpack: ^5.3.0 => 5.3.0
    terser-webpack-plugin: ^3.0.6 => 3.0.6
    webpack: ^4.42.0 => 4.43.0
    webpack-bundle-analyzer: ^3.8.0 => 3.8.0
    webpack-cli: ^3.3.12 => 3.3.12
    webpack-dev-server: 3.10.3 => 3.10.3
    webpack-hot-middleware: ^2.25.0 => 2.25.0
    webpack-merge: ^4.2.2 => 4.2.2
    webpack-node-externals: ^1.7.2 => 1.7.2
  npmGlobalPackages:
    webpack-bundle-analyzer: 3.8.0
</pre>

#### Debug info
```
$ NODE_ENV=production `npm bin`/webpack \
  --config webpack.client.js \
  -o build/client/index.js \
  --profile --json > stats.json
$ webpack-bundle-analyzer stats.json
```
<img width="1440" alt="Screen Shot 2020-07-11 at 8 36 33 AM" src="https://user-images.githubusercontent.com/5452298/87227688-97840380-c351-11ea-9653-e80887078455.png">

[stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/4907036/stats.json.zip)

**Comment by Igloczek** [comment]
Check your Webpack config file, seems like having `stats: 'error-only'` is causing the `stats.json` to have very limited output.

**Comment by divmgl** [comment]
Fantastic, thank you @Igloczek

**Comment by valscion** [comment]
Glad to see that the issue was solved with a configuration change :relaxed:. Would anyone be willing to add that information to the repository README.md, "Troubleshooting" section? https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/370

**Comment by david-wolgemuth** [comment]
I'm also seeing a blank page.  I don't have any `stats:` key for my webpack config.

some of the requirements we're using here:

```
'autoprefixer'
'path'
'webpack'
'html-webpack-plugin'
'mini-css-extract-plugin'
'optimize-css-assets-webpack-plugin'
'webpack-manifest-plugin'
'terser-webpack-plugin'
'react-dev-utils/InterpolateHtmlPlugin'
'sw-precache-webpack-plugin'
'react-dev-utils/eslintFormatter'
'react-dev-utils/ModuleScopePlugin'
'./paths'
'./env'
'compression-webpack-plugin'
'webpack-s3-plugin'
'fork-ts-checker-webpack-plugin'
```

Here's my stats file:

[stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/5797198/stats.json.zip)

Help is appreciated!  The gzipped build ballooned up to ~3MB over the last couple months 😅

**Comment by valscion** [comment]
@david-wolgemuth it could be that `compression-webpack-plugin` is causing your issue, as https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/379 isn't yet done ☺️
