### ISSUE TITLE
Chart assets created by child compilations

### ISSUE THREAD

**Issue by lemonmade** [webpack-contrib/webpack-bundle-analyzer#368]
This plugin currently only traverses the assets in the main compilation (unless there are no assets in the main compilation, in which case it tries to use the first child). Several plugins, like [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin), can generate an additional asset graph that is entirely hidden from analysis. It would be great to have some way of inspecting those assets, too.

I had a need for this recently (to investigate the contents of a web worker asset created via a custom Webpack plugin). The following changeset was able to show the child compilation assets locally: https://github.com/webpack-contrib/webpack-bundle-analyzer/compare/master...lemonmade:add-child-compilations?expand=1. I imagine that change probably breaks other things, but it was nice that it was at least relatively easy to mess with the code and have it work.

**Comment by th0r** [comment]
Could you create a minimal reproduction?

**Comment by masterkidan** [comment]
@th0r Can you please check #150  I’ve added a minimal repro there along with a pr for a potential fix for this issue

**Comment by masterkidan** [comment]
@th0r @lemonmade i believe I’ve referenced a minimal report in #150 and a potential fix in #376

**Comment by lemonmade** [comment]
Thanks @masterkidan, my issue does appear to be a duplicate of the one you've referenced, and the provided example is very much in line with what I am after. Will close this issue in favor of that one!
