### ISSUE TITLE
Unexpected end of JSON when app is very large

### ISSUE THREAD

**Issue by SukantPal** [webpack-contrib/webpack-bundle-analyzer#371]
#### Issue description

The app I was working is very large (~20 MB build unzipped); I think webpack-bundle-analyzer fails when the stats-file is very large (here is 118 MB). The stats-file is unexpectedly _incomplete_.

<img width="787" alt="Screen Shot 2020-07-19 at 12 13 12 PM" src="https://user-images.githubusercontent.com/22450567/87879585-d94c2400-c9b9-11ea-9805-111d88705ee0.png">

#### Technical info

<pre>
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.36 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:

    webpack-bundle-analyzer: ^3.8.0 => 3.8.0
    webpack-modules: ^1.0.0 => 1.0.0
  npmGlobalPackages:
    webpack-bundle-analyzer: 3.8.0
</pre>

___ 
I don't think you want the stats file :). I can upload it if need to.

**Comment by valscion** [comment]
How did you generate the stats file?

**Comment by SukantPal** [comment]
I generated the stats file with the webpack plugin.

**Comment by th0r** [comment]
> with the webpack plugin

Which plugin?

**Comment by SukantPal** [comment]
I used:

```js
BundleAnalyzerPlugin({
  analyzerMode: 'json',
  statsFilename: 'bundle-stats.json'
})
```

**Comment by valscion** [comment]
Hmm if you use

```js
{
  analyzerMode: 'json'
}
```

the file name of the JSON report needs to be specified with `reportFilename`. When `reportFilename` isn't set, it default to `report.json`.

In your screenshot of the text editor, it seems you're looking at the webpack Stats JSON object, and not at the result of the generated JSON report you get when running with `analyzerMode: 'json'`.

If you want to generate the webpack stats JSON file with `webpack-bundle-analyzer`, you need to supply

```js
{
  generateStatsFile: true
}
```

in the plugin options. You could also specify the output stats JSON file explicitly, like so:

```js
BundleAnalyzerPlugin({
  // Generates the webpack Stats JSON object
  generateStatsFile: true,
  // Specifies the location where webpack Stats JSON object will be written to
  statsFileName: 'webpack-stats-from-webpack-bundle-analyzer.json',
  // Disables the bundle size report generation so we only output the webpack Stats JSON object
  analyzerMode: 'disabled'
})
```
