### ISSUE TITLE
openAnalyzer causes crash when run on a server

### ISSUE THREAD

**Issue by wbobeirne** [webpack-contrib/webpack-bundle-analyzer#381]
#### Issue description

The default settings of the plugin have `openAnalyzer: true`, but when I have that set to default on my server, it causes an immediate crash:

```
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at Object.execFile (child_process.js:232:17)
    at opener (/home/coder/c/customer/site/node_modules/opener/lib/opener.js:65:25)
    at Server.<anonymous> (/home/coder/c/customer/site/node_modules/webpack-bundle-analyzer/lib/viewer.js:96:11)
```

Since the opener is pretty non-critical, it'd be nice to just wrap it in a try / catch and log or no-op if it throws.

#### Technical info

<pre>
  System:
    OS: Linux 4.19 Arch Linux
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Memory: 13.44 GB / 58.98 GB
    Container: Yes
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
</pre>

#### Debug info
How do you use this module? **Webpack plugin**

If plugin, what options were provided? **`new BundleAnalyzerPlugin()`**

**Comment by th0r** [comment]
@wbobeirne why not set `openAnalyzer: false` depending on the environment?
