### ISSUE TITLE
Replace deprecated bfj

### ISSUE THREAD

**Issue by TrySound** [webpack-contrib/webpack-bundle-analyzer#383]
#### Issue description

Related pull request https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/129

Looks like all major libraries for streaming json are archived and not gonna be maintained anymore.
- https://github.com/dominictarr/JSONStream
- https://gitlab.com/philbooth/bfj

Here're possible alternatives
- https://github.com/Faleij/json-stream-stringify
- https://github.com/contra/JSONStream (a fork)
- https://github.com/uhop/stream-json

Let's discuss before making changes. Maybe it's not necessary with webpack 5.

**Comment by th0r** [comment]
> Maybe it's not necessary with webpack 5.

Why? Does it introduce some new way to stringify and write huge stats object to disk?

**Comment by TrySound** [comment]
Maybe new stats is not that huge to require this. I'm really not aware about this, just guessing.

**Comment by th0r** [comment]
Fixed in https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/390
