### ISSUE TITLE
Fail to analyze webpack 5 stats.json due to hidden assets

### ISSUE THREAD

**Issue by ZKHelloworld** [webpack-contrib/webpack-bundle-analyzer#385]
#### Issue description
We recently switch webpack to version 5 and webpack-bundle-analyzer fail to analyze.
The error below is logged:
![image](https://user-images.githubusercontent.com/6254209/95726347-68ac5f00-0cab-11eb-911e-0d07dc05591a.png)

#### Debug info
We dive into code and find out the error is produced by this line of code:
![image](https://user-images.githubusercontent.com/6254209/95726808-f7b97700-0cab-11eb-9cf1-91f8d49e0a0a.png)
It turns out that webpack version 5 generates a new kind of assets without a name:
![image](https://user-images.githubusercontent.com/6254209/95727770-37cd2980-0cad-11eb-8776-e8b397051657.png)

We temporary fix this by checking whether `name` is existed or not:
![image](https://user-images.githubusercontent.com/6254209/95728211-d2c60380-0cad-11eb-828a-69fc5370dbf9.png)

**Comment by th0r** [comment]
Could you create a PR?

**Comment by ZKHelloworld** [comment]
@th0r 
Sure.
I shall take some time to investigate what does `hidden assets` means first.

**Comment by ZKHelloworld** [comment]
It seems like webpack 5 change the schema of `assets[*]` and add a new attribute `type` [here](https://github.com/webpack/webpack/commit/d0ef2ce43f2b27318f7971a5b766f4f640e6a55e#diff-68fc93ae89cdcdc16d207fdcfd6e20b5R289)
![image](https://user-images.githubusercontent.com/6254209/95772196-f1002380-0cee-11eb-846e-f1b1dda89323.png)
More types are added [here](https://github.com/webpack/webpack/commit/3ea9400505ba5dc6d422d84e6eb22f1d79adc253)

In our case, we config the `stats.excludeAssets` as:
![image](https://user-images.githubusercontent.com/6254209/95772345-2ad12a00-0cef-11eb-92d9-ef59f40f6e8f.png)
The stats.json contains the `hidden assets` result:
![image](https://user-images.githubusercontent.com/6254209/95772560-826f9580-0cef-11eb-8b48-5036ee82e8ce.png)
Comment out the `stats.excludeAssets`, no `hidden assets` is generated.

It seems like webpack 5 generate more information in stats.json.

-------------------------
Probably a better fix is to check whether the `type` is **asset** or not:
```javascript
  // Picking only `*.js or *.mjs` assets from bundle that has non-empty `chunks` array
  bundleStats.assets = _.filter(bundleStats.assets, asset => {
    // Filter out non 'asset' type asset if type is provided (Webpack 5 add a type to indicate asset types)
    if (asset.type && asset.type !== 'asset') {
      return false;
    }

    // Removing query part from filename (yes, somebody uses it for some reason and Webpack supports it)
    // See #22
    asset.name = asset.name.replace(FILENAME_QUERY_REGEXP, '');

    return FILENAME_EXTENSIONS.test(asset.name) && !_.isEmpty(asset.chunks) && isAssetIncluded(asset.name);
  });
```

**Comment by th0r** [comment]
Fixed in https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/386
