### ISSUE TITLE
webpack5: Unable to view parsed and gzip stats for the main entrypoint

### ISSUE THREAD

**Issue by jamesjia94** [webpack-contrib/webpack-bundle-analyzer#387]
#### Issue description
After upgrading to webpack 5, I notice that the parsed and gzip stats do not show up for the main.[hash].js chunk. All the other chunks are fine.

I confirmed that running it via the cli results in: `Couldn't parse bundle asset ...`

#### Technical info

<pre>
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
  npmPackages:
    compression-webpack-plugin: ^4.0.0 => 4.0.0 
    html-webpack-harddisk-plugin: ^1.0.1 => 1.0.1 
    html-webpack-plugin: ^4.2.1 => 4.3.0 
    webpack: ^5.1.0 => 5.1.3 
    webpack-bundle-analyzer: ^3.8.0 => 3.9.0 
    webpack-cli: 4 => 4.0.0 
    webpack-dev-middleware: ^3.7.2 => 3.7.2 
    webpack-dev-server: ^3.11.0 => 3.11.0 
    webpack-hot-middleware: ^2.25.0 => 2.25.0 
    webpack-merge: ^4.2.2 => 4.2.2 
</pre>

#### Debug info
I normally use it as a plugin, i.e. `new BundleAnalyzerPlugin()`

[stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/5418105/stats.json.zip)

**Comment by th0r** [comment]
> After upgrading to webpack 5, I notice that the parsed and gzip stats do not show up for the main.[hash].js chunk. All the other chunks are fine.

Could you attach a screenshot please that shows that parsed/gzip sizes are missing for `main.[hash].js` chunk, but preset for other chunks please?

**Comment by jamesjia94** [comment]
Of course! Thanks for responding so quickly :)

And sorry, I should've been more specific. The parsed and gziped sizes show up for the main chunk, but not for its contents, so when I view the parsed or gzipped treemap, the main chunk shows up as a big blob.

#### Stat Treemap 
<img width="1780" alt="Screen Shot 2020-10-22 at 8 45 31 AM" src="https://user-images.githubusercontent.com/2763374/96896933-f40fb800-1442-11eb-80db-08783715850b.png">

#### Parsed Treemap
<img width="1785" alt="Screen Shot 2020-10-22 at 8 53 04 AM" src="https://user-images.githubusercontent.com/2763374/96897964-03433580-1444-11eb-9ba4-103adaa4e1f3.png">

**Comment by th0r** [comment]
@jamesjia94 could you check `4.0.0-rc1` and see if bug is fixed?

**Comment by jamesjia94** [comment]
@th0r looks good to me!

**Comment by th0r** [comment]
Fixed in `v4.0.0`
