### ISSUE TITLE
Doesn't respect Webpack "externals"

### ISSUE THREAD

**Issue by tinder-vjancik** [webpack-contrib/webpack-bundle-analyzer#39]
#### Issue description
I use:
```es6
externals: {
  react: 'React',
  'react-dom': 'ReactDOM',
  immutable: 'Immutable',
},
```

and the production bundle size obviously goes down, (by 60kB), but all of those libraries still show up in the bundle composition map of the *bundle-analyzer*.

#### Technical info
* Webpack Bundle Analyzer version: 2.2.1
* Webpack version: 2.2.0
* Node.js version: 6.9.1
* npm/yarn version: npm -> 3.10.8
* OS: OS X 10.12.2

#### Debug info
How do you use this module? As CLI utility or as plugin?
**Plugin**

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```es6
new BundleAnalyzerPlugin({
  analyzerMode: 'server',
  analyzerPort: 8888,
  reportFilename: 'report.html',
  openAnalyzer: true,
  generateStatsFile: false,
  statsFilename: 'stats.json',
  statsOptions: null,
}),
```

What other Webpack plugins were used?
**A lot, but I disabled the CommonsChunkPlugin, to see if it was causing the issue, but it wasn't.**

**Comment by th0r** [comment]
> but all of those libraries still show up in the bundle composition map of the bundle-analyzer

What sizes they have in treemap?

**Comment by th0r** [comment]
@tinder-vjancik Could you provide additional info that I asked [here](https://github.com/th0r/webpack-bundle-analyzer/issues/39#issuecomment-273998251)?

**Comment by th0r** [comment]
@tinder-vjancik If you won't be able to provide additional info I'll have to close this issue because seems like you're the only one that faces it.

**Comment by th0r** [comment]
No info was provided. Closing.

**Comment by richtmat** [comment]
@th0r Hi Yuriy
I have the same problem as we use the external feature heavily. Which information can I provide?

**Comment by richtmat** [comment]
@th0r while preparing a simple repo I figured out that it works. sorry, my bad! I had `"analyze": "npm run build && webpack --profile --json > dist/stats.json && webpack-bundle-analyzer dist/stats.json bundle-analyzer"` and so I was not running webpack in production mode while generating the stats.json file. Now I use `"analyze": "npm run build && webpack --mode production --profile --json > dist/stats.json && webpack-bundle-analyzer dist/stats.json bundle-analyzer"` and externals are not shown as I expected.
