### ISSUE TITLE
postcss v8 compatibility

### ISSUE THREAD

**Issue by therealgilles** [webpack-contrib/webpack-bundle-analyzer#416]
#### Issue description
Running with postcss v8 generates the following warning due to the cssnano dependency:

```
cssnano: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

#### Technical info
<pre>
  System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 56.98 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  npmPackages:
    webpack: ^4.44.1 => 4.46.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 
</pre>

#### Debug info
I use the module as a plugin used by razzle-plugin-bundle-analyzer.
No options provided.

Stats.json file:
[stats.json.log](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/5947382/stats.json.log)

**Comment by valscion** [comment]
`cssnano` is in devDependencies, are you sure `webpack-bundle-analyzer` is the one that is giving you the `cssnano` warning?

**Comment by therealgilles** [comment]
Thanks for your response @valscion. Maybe I got it wrong, let me try to narrow it down.

**Comment by th0r** [comment]
@therealgilles try `npm ls cssnano` to check where does it come from.
