### ISSUE TITLE
remove FoamTree icon

### ISSUE THREAD

**Issue by ClassJm** [webpack-contrib/webpack-bundle-analyzer#420]
#### Issue description
Can I remove the FoamTree icon and use webpack-bundle-analyzer in my product？Is the MIT license violated?

![image](https://user-images.githubusercontent.com/20009923/110621000-b1bdfc00-81d4-11eb-9a97-1cbfdb9e778c.png)

**Comment by valscion** [comment]
No you can't remove FoamTree icon: https://carrotsearch.com/foamtree/free-trial/

> **Can I use the demo version in a commercial project?**
> 
> Yes, feel free to use the demo version in your project free of charge. The only requirement is that you must not remove or obscure the FoamTree logo the demo version displays.

The FoamTree package is a dependency of this library, so MIT license for the code in this repository is not violated as far as I have understood it.
