### ISSUE TITLE
modules not showing in a certain configuration

### ISSUE THREAD

**Issue by deanshub** [webpack-contrib/webpack-bundle-analyzer#437]
#### Issue description
modules not showing

#### Technical info

<pre>
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 100.89 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/gm/xwxrzmpx48s2zmt_wr40tdknylqlq3/T/fnm_multishells/84828_1618916195681/bin/node
    Yarn: 1.22.10 - /var/folders/gm/xwxrzmpx48s2zmt_wr40tdknylqlq3/T/fnm_multishells/84828_1618916195681/bin/yarn
    npm: 6.14.11 - /var/folders/gm/xwxrzmpx48s2zmt_wr40tdknylqlq3/T/fnm_multishells/84828_1618916195681/bin/npm
</pre>

#### Debug info
Using the module as CLI utility
```sh
npx webpack-bundle-analyzer@latest target/webpack-stats.json dist/statics -s stat
```
for one webpack.stats with 3 entries all works well, when I remove one of the entries (a specific one) the node modules aren't showing

Good:
![image](https://user-images.githubusercontent.com/2688676/116518334-c6676800-a8d8-11eb-9756-768ebbc29172.png)

Bad:
![image](https://user-images.githubusercontent.com/2688676/116518384-d717de00-a8d8-11eb-97fd-2b8e22a17c6e.png)

Going to debug and fix this so if you have any insights, it'll help

**Comment by valscion** [comment]
Sorry, no insights to provide with this information

**Comment by Schniz** [comment]
From my digging it looks like the stats file was generated using `chunkModules: false`, and WBA doesn't have the data it needs to generate the drilled-down report.

**Comment by valscion** [comment]
So you mean the stats file was generated with `stats.chunkModules: false` as in documented here? https://webpack.js.org/configuration/stats/#statschunkmodules

So yeah, indeed tweaking what the `stats` option values are does affect what `webpack-bundle-analyzer` outputs.

So it seems that WBA is working as expected, so I'll close this issue ☺️
