### ISSUE TITLE
Webpack `5.34.0` ➞ `5.36.1` breaks compatibility with `webpack-bundle-analyzer`

### ISSUE THREAD

**Issue by yoav-lavi** [webpack-contrib/webpack-bundle-analyzer#438]
#### Issue description
Twin issue on Webpack: https://github.com/webpack/webpack/issues/13278

An update between `5.34.0` -> `5.36.1` on Webpack broke typing compatibility with `BundleAnalyzerPlugin`. This seems to be due to still using `@types/webpack` in `webpack-bundle-analyzer` (which as far as I'm aware is now bundled internally in Webpack)

Error:

```
webpack.config.ts:152:3 - error TS2322: Type '(ReactRefreshPlugin | DefinePlugin | DuplicatesPlugin | BundleAnalyzerPlugin | HotModuleReplacementPlugin)[]' is not assignable to type '(((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance)[]'.
  Type 'ReactRefreshPlugin | DefinePlugin | DuplicatesPlugin | BundleAnalyzerPlugin | HotModuleReplacementPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
    Type 'BundleAnalyzerPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
      Type 'BundleAnalyzerPlugin' is not assignable to type 'WebpackPluginInstance'.
        Types of property 'apply' are incompatible.
          Type '(compiler: import("/node_modules/@types/webpack-bundle-analyzer/node_modules/webpack/types").Compiler) => void' is not assignable to type '(compiler: import("/node_modules/webpack/types").Compiler) => void'.
            Types of parameters 'compiler' and 'compiler' are incompatible.
              Type 'import("/node_modules/webpack/types").Compiler' is not assignable to type 'import("/node_modules/@types/webpack-bundle-analyzer/node_modules/webpack/types").Compiler'.
                The types of 'hooks.shouldEmit' are incompatible between these types.
                  Type 'import("/node_modules/tapable/tapable").SyncBailHook<[import("/node_modules/webpack/types").Compilation], boolean, import("/node_modules/tapable/tapable").UnsetAdditionalOptions>' is not assignable to type 'import("/node_modules/tapable/tapable").SyncBailHook<[import("/node_modules/@types/webpack-bundle-analyzer/node_modules/webpack/types").Compilation], boolean, import("/node_modules/tapable/tapable").UnsetAdditionalOptions>'.
```

#### Technical info

<pre>
  System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 215.81 MB / 16.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  npmPackages:
    compression-webpack-plugin: ^7.1.2 => 7.1.2 
    lodash-webpack-plugin: ^0.11.6 => 0.11.6 
    stylelint-webpack-plugin: ^2.0.0 => 2.1.1 
    webpack: ^5.36.1 => 5.36.1 
    webpack-bundle-analyzer: ^4.4.1 => 4.4.1 
    webpack-cli: ^4.6.0 => 4.6.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 
</pre>

#### Debug info

I use `webpack-bundle-analyzer` as a plugin:

```ts
new BundleAnalyzerPlugin({
      openAnalyzer: false,
      defaultSizes: 'gzip',
      analyzerMode: 'static',
      reportFilename: 'file-name.html',
    }),
```

**Comment by th0r** [comment]
Sorry, but we don't maintain TS types in this package - you'll have to move your issue to https://github.com/DefinitelyTyped/DefinitelyTyped repo.
