### ISSUE TITLE
There is a vulnerability introduced by package ejs

### ISSUE THREAD

**Issue by paimon0715** [webpack-contrib/webpack-bundle-analyzer#460]
Hi, @th0r @valscion, 
### Issue Description
I accidentally find a vulnerability introduced in your package **webpack-bundle-analyzer** and the vulnerability [**SNYK-JS-EJS-1049328**](https://snyk.io/vuln/SNYK-JS-EJS-1049328) is detected in package **ejs<3.1.6**. Unfortunately,**_webpack-bundle-analyzer@3.9.0_** directly depends on **ejs@2.7.4**. 
  
   As far as I know,  **_webpack-bundle-analyzer@3.9.0_** is so popular that a large number of active and popular downstream projects depend on it in their latest versions ([1,171,406 downloads per week](https://www.npmjs.com/package/webpack-bundle-analyzer/v/3.9.0?activeTab=versions) and about **1,406 downstream projects**, e.g., @vue/cli-service 4.5.13, @xdn/core 2.53.3, @factor/core 1.8.30, react-static 7.5.3, graphql-playground-react 1.7.27, @formily/meet-components 1.3.17, mkui-fd 3.2.21, etc.). 
As such, issue [**SNYK-JS-EJS-1049328**](https://snyk.io/vuln/SNYK-JS-EJS-1049328) can be propagated into these downstream projects and expose security threats to them.
   
  As you can see, **_webpack-bundle-analyzer@3.9.0_** is introduced into the above projects via the following package dependency paths:
(1)`@formily/meet-components@1.3.17 ➔ rax-plugin-app@0.2.19 ➔ webpack-bundle-analyzer@3.9.0 ➔ ejs@2.7.4`
(2)`mkui-fd@3.2.21 ➔ @packtracker/webpack-plugin@2.3.0 ➔ webpack-bundle-analyzer@3.9.0 ➔ ejs@2.7.4`
    **......**
   I have konwn that it's kind of you to have removed such a vulnerability since **_webpack-bundle-analyzer@4.0.0-rc1_**. However, these projects cannot easily upgrade **webpack-bundle-analyzer** from version **_3.9.0_** to _**(>=4.0.0-rc1)**_:
The projects such as **rax-plugin-app** and **@packtracker/webpack-plugin**, which introduced webpack-bundle-analyzer@3.9.0, are not maintained anymore. These unmaintained packages can neither upgrade **webpack-bundle-analyzer** nor be easily migrated by the large amount of affected downstream projects.  

 **Given the large number of downstream users, is it possible to release a new patched version with the updated dependency to remove the vulnerability from webpack-bundle-analyzer@3.9.0?**

### Suggested Solution

As you know, since these inactive projects set a version constaint **3.9.\*** for **webpack-bundle-analyzer** on the above vulnerable dependency paths, if **webpack-bundle-analyzer** removes the vulnerability from 3.9.0 and releases a new patched version **_webpack-bundle-analyzer@3.9.1_**, such a vulnerability patch can be automatically propagated into the 1,406 affected downstream projects.

Maybe the simplest way to remove the vulnerability is to perform the following upgrade in **_webpack-bundle-analyzer@3.9.1_**:
`ejs ^2.6.1 ➔ ^3.1.6`;  
**Note:**
**_ejs@3.1.6(>=3.1.6)_** has fixed the vulnerability ([**SNYK-JS-EJS-1049328**](https://snyk.io/vuln/SNYK-JS-EJS-1049328)).
Of course, you are welcome to share your idea with me.^_^

Thank you for your help.

**Comment by valscion** [comment]
`webpack-bundle-analyzer` is a development-only tool so this vulnerability report does not concern us.

We will update the dependencies on our own pace and at that time, this issue will also be fixed.

This is a similar issue as written here: https://overreacted.io/npm-audit-broken-by-design/

**Comment by cwilby** [comment]
Hey - I totally get the "development-only" approach.  But please, understand - you don't speak for everybody, it matters in some environments - particularly financial - where we are targeted constantly.
