### ISSUE TITLE
Crashes if I try to pass custom arguments to process.argv from scripts in package.json

### ISSUE THREAD

**Issue by Profesor08** [webpack-contrib/webpack-bundle-analyzer#467]
#### Issue description
Get crash if I try to pass custom arguments to `process.argv` from scripts in **package.json**

#### Technical info

If I add to `scripts` in **package.json** some additional props, I get error:
```
> npm run build:analize

> project@1.0.0 build:analize
> webpack --mode production --progress --no-devtool -- --analizefff

99% done plugins webpack-bundle-analyzerWebpack Bundle Analyzer saved report to E:\project_root
65 assets

ERROR in main
Module not found: Error: Can't resolve '--analize' in 'E:\project_root'

webpack 5.41.0 compiled with 1 error in 4825 ms
```

**package.json**
```json
{
  "scripts": {
    "build:analize": "webpack --mode production --progress --no-devtool -- --analize",
  },
}
```

#### Debug info
How do you use this module? As CLI utility or as plugin?
as plugin

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```js
  if (process.argv.includes("--analize")) {
    plugins.push(new BundleAnalyzerPlugin());
  }
```

`stats.json` will be created in Webpack bundle output directory.
no stats.json, it crashes.

**Comment by alexander-akait** [comment]
Please use https://webpack.js.org/api/cli/#env

**Comment by Profesor08** [comment]
> Please use https://webpack.js.org/api/cli/#env, unknown options forbidden, for any custom options you need to use `--env`

So, this mean what this plugin analyze only scripts related to webpack **only**? And if it finds some unknown parameter, it crashes? But for other scripts, not related to webpack, it will be ok?

**Comment by valscion** [comment]
It means that the error you're seeing is not something that `webpack-bundle-analyzer` code takes care of. `webpack` itself does not allow unknown options, so you need to use `--env` to pass custom options you can later write conditionals against.
