### ISSUE TITLE
Error parsing bundle asset "dist\js\chunk-vendors.js": no such file

### ISSUE THREAD

**Issue by Vector-Green** [webpack-contrib/webpack-bundle-analyzer#485]
#### Issue description
I'm getting a console error using ```yarn serve```
```
Error parsing bundle asset "C:\bundle_analyzer_test\dist\js\chunk-vendors.js": no such file
Error parsing bundle asset "C:\bundle_analyzer_test\dist\js\app.js": no such file
Error parsing bundle asset "C:\bundle_analyzer_test\dist\js\about.js"": no such file
```
Although the BundleAnalyzerPlugin itself displays all modules correctly in both (yarn serve/ yarn build)
No console errors occur when using ```yarn build```.

#### Technical info
<pre>
  System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
    Memory: 4.51 GB / 10.96 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
</pre>

#### Project presset 
```
  "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": true
        },
        "@vue/cli-plugin-vuex": {},
        "@vue/cli-plugin-eslint": {
          "config": "prettier",
          "lintOn": [
            "save"
          ]
        },
        "@vue/cli-plugin-unit-jest": {},
        "@vue/cli-plugin-e2e-cypress": {}
      },
      "vueVersion": "3",
      "cssPreprocessor": "dart-sass"

webpack@5.64.4
vue@3.2.23
@vue/cli 5.0.0-rc.1
```

I'm using as webpack plugin webpack-bundle-analyzer@4.5.0

```
//vue.config.js
const { defineConfig } = require("@vue/cli-service");

const BundleAnalyzerPlugin =
  require("webpack-bundle-analyzer").BundleAnalyzerPlugin;

module.exports = defineConfig({
  transpileDependencies: true,

  chainWebpack: (config) => {
      config.plugin("BundleAnalyzerPlugin").use(BundleAnalyzerPlugin, [
        {
          analyzerMode: "server",
          openAnalyzer: true,
        },
      ]);
  },
});
```

What other Webpack plugins were used? Default vue/cli 
```
[
  'vue-loader',
  'feature-flags',
  'define',
  'case-sensitive-paths',
  'friendly-errors',
  'html',
  'copy',
  'eslint',
  'fork-ts-checker',
  'BundleAnalyzerPlugin'
]
```

GitHub's project with the issue https://github.com/Vector-Green/BundleAnalyzerPluginIssue
[stats.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/7628183/stats.zip)

**Comment by valscion** [comment]
This is expected scenario as with `yarn serve`,  is uses `webpack-dev-server` underneath and doesn't generate the bundle files to disk. So `webpack-bundle-analyzer` can't analyze your build files.

https://github.com/webpack-contrib/webpack-bundle-analyzer#i-dont-see-gzip-or-parsed-sizes-it-only-shows-stat-size
