### ISSUE TITLE
Feature Request: Website!

### ISSUE THREAD

**Issue by vincerubinetti** [webpack-contrib/webpack-bundle-analyzer#497]
Thanks for the great tool.

Other [similar tools](https://blog.bitsrc.io/6-tools-and-techniques-to-analyze-webpack-bundle-size-817337f8cf91) have a website where you can just upload the webpack-generated `stats.json` file to, and see the visualization there, no installation required.

This library's visualization is better than the others' imo, and it's the most popular. It'd be nice if people had a convenient way to test it out.

**Comment by valscion** [comment]
With only the stats JSON file, there's less useful info. We'd need the entire bundle to be uploaded together with stats file to get parsed ans gzipped sizes.

Honestly this feature would be such a large undertaking that another whole project would be suitable for that. Anyone can feel free to create such a project and we can then link to it, once it is working, from this project's readme.

**Comment by valscion** [comment]
The CLI reads the generated files in dist/ folder in your case, too, as that's where the stats.json file is, too. That is why you see gzip and parsed sizes in your screenshot :)
