### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: sirv is not a function

### ISSUE THREAD

**Issue by renzp94** [webpack-contrib/webpack-bundle-analyzer#528]
#### Issue description
...

#### Technical info

<pre>
  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 37.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
</pre>

#### Debug info

<pre>
"webpack": "^5.74.0",
"webpack-bundle-analyzer": "^4.6.1",
</pre>

(node:20919) UnhandledPromiseRejectionWarning: TypeError: sirv is not a function
    at Object.startServer
    at BundleAnalyzerPlugin2.startAnalyzerServer 

```js
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'

webpackChain.plugin('webpack-bundle-analyzer').use(BundleAnalyzerPlugin)
```

**Comment by valscion** [comment]
I've never seen this `webpackChain.plugin(...).use()` format, where does it come crom? Can you test whether this error happens without the webpack chain usage?

**Comment by renzp94** [comment]
> I've never seen this `webpackChain.plugin(...).use()` format, where does it come crom? Can you test whether this error happens without the webpack chain usage?

I can use the webpack is ok. It may be the problem that I use the webpack chain.

**Comment by renzp94** [comment]
I can delete the node_modules and download it again. It may be that there is a problem with the dependency. Sorry to bother you.
