### ISSUE TITLE
[Question] Chrome performance issue

### ISSUE THREAD

**Issue by LitileXueZha** [webpack-contrib/webpack-bundle-analyzer#534]
#### Issue description

I'm not sure this is caused by the plugin or my system.

It's a very strange behavior: the output page is very slow when moving the mouse, at the same time, GPU usage is jump to 100%.

![image](https://user-images.githubusercontent.com/22041474/199971205-3a809d37-6637-4039-a3d8-ab26a9d05edd.png)

It's only occurred in Google Chrome, and in the Microsoft Edge is normal.

#### Technical info
+ Windows 10, x64
+ Chrome 106.0.5249.62
+ Edge 105.0.1343.53

#### Debug info

[zzz-analyzer.html.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/9938154/zzz-analyzer.html.txt)

Github not allow the `.html` extension files, please remove the `.txt` suffix to view this HTML file.

**Comment by valscion** [comment]
If someone with a Windows machine could test whether this is reproducible that would be great.

We could also try if we're running an out-of-date version of FoamTree and see if updating it would fix any possibly existing performance issue.

**Comment by LitileXueZha** [comment]
Tried again today, and the performance of moving mouse is reasonable, the behavior disappeared, so close it.
