### ISSUE TITLE
Could't analyze webpack bundle: TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by qyjs** [webpack-contrib/webpack-bundle-analyzer#605]
angular 16.1.3
webpack-bundle-analyzer 4.9.0

I execute a command line startup error

![image](https://github.com/webpack-contrib/webpack-bundle-analyzer/assets/22796811/ca8b7ea1-368c-415a-bdd6-906e261be535)

**Comment by th0r** [comment]
Fill issue template please.

**Comment by chrismclarke** [comment]
I received the same message, it's because angular now includes esbuild and so the corresponding stats.json should be analyzed with https://esbuild.github.io/analyze/ and not webpack-bundle-analyzer. 

If still having issues probably best to open issue on the angular-cli repo instead.

**Comment by duxor** [comment]
@chrismclarke is there any way to run it from CLI like a `webpack-bundle-analyzer`?
