### ISSUE TITLE
Filter by entry point

### ISSUE THREAD

**Issue by chriskrogh** [webpack-contrib/webpack-bundle-analyzer#623]
### Discussed in https://github.com/webpack-contrib/webpack-bundle-analyzer/discussions/622

<div type='discussions-op-text'>

<sup>Originally posted by **chriskrogh** November  8, 2023</sup>
At Faire, we use [@next/bundle-analyzer](https://www.npmjs.com/package/@next/bundle-analyzer) (which is just a [wrapper around webpack-bundle-analyzer](https://github.com/vercel/next.js/blob/76def31fb208d2df70a707edbc7a9ab9945d58cc/packages/next-bundle-analyzer/index.js#L7C12-L7C12)) to understand our page weight. 
We currently have > 450 "routes" in our next app and the current entrypoint dropdown makes it really difficult for teams to find the route they care about.

it'd be great if we could filter the list of entry points by typing into the input before selecting an option.

</div>

**Comment by valscion** [comment]
Discussion in #622
