### ISSUE TITLE
Support for vite?

### ISSUE THREAD

**Issue by windmillcode0** [webpack-contrib/webpack-bundle-analyzer#629]
### Feature request
any support for vite?

**Comment by th0r** [comment]
Vite uses webpack?

**Comment by windmillcode0** [comment]
however when we run analyze on our angular vite application we get errors 
TypeError: Cannot read properties of undefined (reading 'filter') 
Here was the full issue we raised with the angular team
https://github.com/angular/angular-cli/issues/27190

**Comment by evenstensberg** [comment]
Vite runs on Rollup, not webpack

**Comment by windmillcode0** [comment]
So I suppose no support? then

**Comment by alexander-akait** [comment]
@windmillcode0 The original issue https://github.com/angular/angular-cli/issues/27190 is not about vite, it is about `stat.json` without assets, but without this fields we can't undestand generated files

**Comment by windmillcode0** [comment]
theres [vite-bundle-visualizer](https://www.npmjs.com/package/vite-bundle-visualizer) but their UI is not sophiscated as your mabyue you can take a look

**Comment by th0r** [comment]
I think it's better to open issue in their repo to improve UI then.

**Comment by windmillcode0** [comment]
Very well I was wondering if this tool can do both, and become the go to tool, we might make a PR
